import { CONFIG } from './config.js'
const $=id=>document.getElementById(id)
const token=new URLSearchParams(location.hash.replace(/^#/, '')).get('acesso')||''
const mascots=['🐼','🐰','🦊','🐱','🐶','🐻','🐨','🦄','🐸','🐯','🦋','🌷','⭐','💜']
async function rpc(name,args={}){const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${CONFIG.SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(args),cache:'no-store'});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.message||'Não foi possível concluir.');return d}
async function media(payload){const r=await fetch(`${CONFIG.SUPABASE_URL}/functions/v1/friend-media`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${CONFIG.SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||'Não foi possível carregar o perfil.');return d}
function toast(t){const x=$('friendToast');if(!x)return;x.textContent=t;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),1800)}
function avatarButton(){return $('friendAvatarBtn')}
function applyEmoji(e){const b=avatarButton();if(!b)return;b.textContent=e;b.style.backgroundImage='none';b.classList.remove('has-photo')}
function applyPhoto(url){const b=avatarButton();if(!b)return;b.textContent='';b.style.backgroundImage=`url("${url}")`;b.classList.add('has-photo')}
async function refresh(){try{const b=await rpc('friend_portal_bootstrap',{p_token:token});const ref=b?.friend?.avatarRef||'';if(ref.startsWith('emoji:'))applyEmoji(ref.slice(6));else if(ref){const d=await media({action:'profile_signed_url',token});if(d?.url)applyPhoto(d.url)}}catch{}}
function openDialog(){const d=$('friendProfileDialog');if(!d)return;$('friendMascotGrid').innerHTML=mascots.map(e=>`<button type="button" data-friend-mascot="${e}">${e}</button>`).join('');d.showModal();document.querySelectorAll('[data-friend-mascot]').forEach(b=>b.onclick=async()=>{try{await rpc('friend_portal_set_mascot',{p_token:token,p_emoji:b.dataset.friendMascot});applyEmoji(b.dataset.friendMascot);d.close();toast('Mascote salvo ✓')}catch(e){toast(e.message)}})}
async function upload(file){if(!file)return;if(file.size>6*1024*1024)return toast('Use uma imagem de até 6 MB.');const form=new FormData();form.append('action','profile');form.append('token',token);form.append('file',file);try{const r=await fetch(`${CONFIG.SUPABASE_URL}/functions/v1/friend-media`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${CONFIG.SUPABASE_KEY}`},body:form});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||'Não foi possível trocar a foto.');if(d?.url)applyPhoto(d.url);$('friendProfileDialog')?.close();toast('Foto do perfil atualizada ✓')}catch(e){toast(e.message)}}
function bind(){const a=avatarButton();if(a&&!a.dataset.profileBound){a.dataset.profileBound='1';a.onclick=openDialog}$('friendProfileEditBtn')?.addEventListener('click',openDialog,{once:true});$('friendProfileClose')?.addEventListener('click',()=>$('friendProfileDialog')?.close(),{once:true});$('friendChoosePhoto')?.addEventListener('click',()=>{$('friendProfileDialog')?.close();$('friendProfilePhotoInput')?.click()},{once:true});const input=$('friendProfilePhotoInput');if(input&&!input.dataset.profileBound){input.dataset.profileBound='1';input.onchange=e=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value=''}}}
window.addEventListener('load',()=>{bind();setTimeout(refresh,300)});bind()
