import { CONFIG } from './config.js'
const $=id=>document.getElementById(id)
let me=null,checking=false,currentAlarm=null,audioCtx=null
function sessionToken(){try{const ref=new URL(CONFIG.SUPABASE_URL).hostname.split('.')[0],raw=localStorage.getItem(`sb-${ref}-auth-token`);if(!raw)return null;const d=JSON.parse(raw);return d?.access_token||d?.currentSession?.access_token||d?.session?.access_token||null}catch{return null}}
function jwtSub(token){try{return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).sub||null}catch{return null}}
async function identity(){if(me)return me;const token=sessionToken();if(!token)throw new Error('Sem sessão');const sub=jwtSub(token);const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/family_members?select=id,family_id,display_name,role&auth_user_id=eq.${encodeURIComponent(sub)}&active=eq.true&limit=1`,{headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${token}`},cache:'no-store'});const rows=await r.json();if(!r.ok||!rows?.[0])throw new Error('Perfil não encontrado');me=rows[0];return me}
function isIsa(){return String($('myName')?.textContent||'').trim().toLowerCase()==='isa'}
function toast(text){const t=$('toast');if(!t)return;t.textContent=text;t.classList.remove('hidden');clearTimeout(t._al);t._al=setTimeout(()=>t.classList.add('hidden'),2500)}
function localDateInput(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function localTimeInput(d=new Date(Date.now()+3600000)){return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function ensureCss(){if($('calendarAlarmCss'))return;const s=document.createElement('style');s.id='calendarAlarmCss';s.textContent='.alarm-modal{position:fixed;inset:0;z-index:260;background:rgba(68,49,82,.28);backdrop-filter:blur(5px);display:grid;place-items:center;padding:18px}.alarm-card{width:min(460px,94vw);padding:22px;border-radius:28px;background:linear-gradient(145deg,#fffafd,#eee5ff);box-shadow:0 24px 60px rgba(75,54,91,.25)}.alarm-card h3{margin:0 0 6px}.alarm-card label{display:block;font-weight:800;font-size:.82rem;margin:12px 0 5px}.alarm-card input,.alarm-card select{width:100%;padding:11px 12px;border:1px solid #eee1f3;border-radius:14px;background:#fff}.alarm-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.alarm-actions{display:flex;gap:8px;margin-top:15px}.alarm-actions button{flex:1;border:0;border-radius:14px;padding:11px;font-weight:900}.alarm-primary{background:linear-gradient(145deg,#c6aff8,#eba7c8);color:#fff}.alarm-soft{background:#f1e9ff}.alarm-ring{position:fixed;inset:0;z-index:300;background:radial-gradient(circle at 50% 35%,rgba(255,255,255,.94),rgba(238,226,255,.96));display:grid;place-items:center;padding:20px}.alarm-ring-card{width:min(520px,94vw);text-align:center;padding:32px;border-radius:32px;background:linear-gradient(145deg,#fff4c7,#ffdfea 50%,#e3d6ff);box-shadow:0 25px 65px rgba(76,55,93,.24)}.alarm-clock{font-size:72px;animation:ring 1s infinite}@keyframes ring{0%,100%{transform:rotate(-4deg)}50%{transform:rotate(4deg)}}.alarm-ring-card h2{margin:8px 0}.alarm-ring-actions{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-top:18px}.alarm-ring-actions button{border:0;border-radius:14px;padding:11px;font-weight:900;background:#fff}.alarm-ring-actions .done{background:#dff3e5}.alarm-chip{display:inline-flex;align-items:center;gap:5px;padding:7px 10px;border-radius:12px;background:#fff1bd;font-size:.76rem;font-weight:900;margin-left:7px}@media(max-width:620px){.alarm-grid,.alarm-ring-actions{grid-template-columns:1fr}}';document.head.appendChild(s)}
function ensureButton(){if(!isIsa())return;const head=document.querySelector('.calendar-panel-title');if(!head||$('newAlarmBtn'))return;const b=document.createElement('button');b.id='newAlarmBtn';b.type='button';b.className='soft-btn';b.textContent='⏰ Alarme';b.onclick=openAlarmDialog;head.appendChild(b)}
function openAlarmDialog(){ensureCss();document.getElementById('alarmModal')?.remove();const d=document.createElement('div');d.id='alarmModal';d.className='alarm-modal';d.innerHTML=`<div class="alarm-card"><h3>⏰ Novo alarme da Isa</h3><p style="color:#8c7e94;margin:0">O compromisso entra no seu calendário e toca no Cantinho quando chegar a hora.</p><label>Título</label><input id="alarmTitle" maxlength="120" placeholder="Ex.: Fazer atividade de Ciências"><div class="alarm-grid"><label>Data<input id="alarmDate" type="date" value="${localDateInput()}"></label><label>Hora<input id="alarmTime" type="time" value="${localTimeInput()}"></label></div><label>Avisar antes</label><select id="alarmReminder"><option value="0">Na hora</option><option value="5">5 minutos antes</option><option value="10" selected>10 minutos antes</option><option value="30">30 minutos antes</option><option value="60">1 hora antes</option></select><div class="alarm-actions"><button id="cancelAlarmBtn" class="alarm-soft" type="button">Cancelar</button><button id="saveAlarmBtn" class="alarm-primary" type="button">Salvar alarme</button></div><p id="alarmMsg" style="min-height:20px;font-size:.78rem;margin:9px 0 0"></p></div>`;document.body.appendChild(d);$('cancelAlarmBtn').onclick=()=>d.remove();$('saveAlarmBtn').onclick=saveAlarm}
async function saveAlarm(){const title=$('alarmTitle').value.trim(),date=$('alarmDate').value,time=$('alarmTime').value;if(!title||!date||!time){$('alarmMsg').textContent='Preencha título, data e hora.';return}const token=sessionToken();try{const u=await identity(),starts=new Date(`${date}T${time}:00`);if(isNaN(starts)||starts<Date.now()-60000)throw new Error('Escolha um horário futuro.');$('saveAlarmBtn').disabled=true;const body={family_id:u.family_id,created_by:u.id,title,description:'Alarme pessoal da Isa',starts_at:starts.toISOString(),ends_at:null,all_day:false,category:'alarme',visibility_member_ids:[],alarm_enabled:true,alarm_reminder_minutes:Number($('alarmReminder').value||0),alarm_fired_at:null,alarm_snoozed_until:null};const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/family_calendar`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(body)});let e=null;try{e=await r.json()}catch{}if(!r.ok)throw new Error(e?.message||'Não foi possível salvar o alarme.');document.getElementById('alarmModal')?.remove();toast('Alarme salvo no calendário ⏰');setTimeout(checkAlarms,300)}catch(e){$('alarmMsg').textContent=e.message}finally{if($('saveAlarmBtn'))$('saveAlarmBtn').disabled=false}}
async function dueAlarms(){const token=sessionToken(),u=await identity(),from=new Date(Date.now()-86400000).toISOString(),to=new Date(Date.now()+172800000).toISOString();const q=`select=id,title,starts_at,alarm_reminder_minutes,alarm_fired_at,alarm_snoozed_until&created_by=eq.${u.id}&alarm_enabled=eq.true&starts_at=gte.${encodeURIComponent(from)}&starts_at=lte.${encodeURIComponent(to)}&order=starts_at.asc`;const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/family_calendar?${q}`,{headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)return[];return r.json()}
async function checkAlarms(){if(checking||!isIsa()||!sessionToken())return;checking=true;try{const list=await dueAlarms(),now=Date.now();for(const e of list){const start=new Date(e.starts_at).getTime(),due=e.alarm_snoozed_until?new Date(e.alarm_snoozed_until).getTime():start-Number(e.alarm_reminder_minutes||0)*60000;if(now>=due&&now<start+6*3600000&&!e.alarm_fired_at){await fireAlarm(e);break}}}catch{}finally{checking=false}}
function beep(){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const now=audioCtx.currentTime;[0,.38,.76].forEach((offset,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=i===1?880:720;g.gain.setValueAtTime(.0001,now+offset);g.gain.exponentialRampToValueAtTime(.18,now+offset+.02);g.gain.exponentialRampToValueAtTime(.0001,now+offset+.28);o.connect(g).connect(audioCtx.destination);o.start(now+offset);o.stop(now+offset+.3)})}catch{}}
async function browserNotice(e){if(!('Notification'in window)||Notification.permission!=='granted')return;try{const reg=await navigator.serviceWorker.ready;await reg.showNotification('⏰ '+e.title,{body:'Alarme do calendário da Isa',icon:'icon.svg',tag:`isa-alarm-${e.id}`,renotify:true})}catch{try{new Notification('⏰ '+e.title,{body:'Alarme do calendário da Isa',icon:'icon.svg'})}catch{}}}
async function markFired(id){const token=sessionToken();await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/family_calendar?id=eq.${id}`,{method:'PATCH',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({alarm_fired_at:new Date().toISOString()})})}
async function fireAlarm(e){currentAlarm=e;await markFired(e.id);beep();browserNotice(e);showRing(e)}
function showRing(e){document.getElementById('alarmRing')?.remove();const d=document.createElement('div');d.id='alarmRing';d.className='alarm-ring';d.innerHTML=`<div class="alarm-ring-card"><div class="alarm-clock">⏰</div><small>Alarme do Meu Calendário</small><h2>${String(e.title||'Compromisso').replace(/[&<>"']/g,'')}</h2><p>${new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(e.starts_at))}</p><div class="alarm-ring-actions"><button data-snooze="5" type="button">Adiar 5 min</button><button data-snooze="10" type="button">Adiar 10 min</button><button id="finishAlarmBtn" class="done" type="button">✓ Concluir</button></div></div>`;document.body.appendChild(d);d.querySelectorAll('[data-snooze]').forEach(b=>b.onclick=()=>snooze(Number(b.dataset.snooze)));$('finishAlarmBtn').onclick=finishAlarm}
async function snooze(min){if(!currentAlarm)return;const token=sessionToken(),until=new Date(Date.now()+min*60000).toISOString();await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/family_calendar?id=eq.${currentAlarm.id}`,{method:'PATCH',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({alarm_snoozed_until:until,alarm_fired_at:null})});document.getElementById('alarmRing')?.remove();toast(`Alarme adiado por ${min} minutos`);currentAlarm=null}
async function finishAlarm(){if(!currentAlarm)return;const token=sessionToken();await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/family_calendar?id=eq.${currentAlarm.id}`,{method:'PATCH',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({alarm_enabled:false,alarm_snoozed_until:null})});document.getElementById('alarmRing')?.remove();toast('Alarme concluído ✓');currentAlarm=null}
const obs=new MutationObserver(()=>ensureButton());obs.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});window.addEventListener('load',()=>setTimeout(()=>{ensureCss();ensureButton();checkAlarms()},800));setInterval(()=>{ensureButton();checkAlarms()},15000);document.addEventListener('click',()=>{if(audioCtx?.state==='suspended')audioCtx.resume().catch(()=>{})},{once:true})