import { CONFIG } from './config.js'

const $=id=>document.getElementById(id), extToken=new URLSearchParams(location.hash.slice(1)).get('acesso')||''
const extMode=!!extToken&&!!$('friendApp')
let currentConv=null, currentCtx=null, active=null, incoming=null, pollTimer=null, lastClicked=null, ringStop=null

function getAuth(){
  const seek=o=>{if(!o||typeof o!=='object')return'';if(typeof o.access_token==='string')return o.access_token;for(const v of Object.values(o)){const t=seek(v);if(t)return t}return''}
  for(const store of [localStorage,sessionStorage]){try{for(let i=0;i<store.length;i++){const k=store.key(i)||'';if(!/auth-token/i.test(k))continue;let raw=store.getItem(k)||'';if(raw.startsWith('base64-')){try{raw=atob(raw.slice(7))}catch{}}try{const t=seek(JSON.parse(raw));if(t)return t}catch{}}}catch{}}
  return''
}
async function rpc(name,args={}){
  const bearer=extMode?CONFIG.SUPABASE_KEY:getAuth();if(!bearer)throw new Error('Entre novamente no Cantinho para usar chamadas.')
  const body={...args,p_token:extMode?extToken:null}
  const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',cache:'no-store',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${bearer}`,'Content-Type':'application/json'},body:JSON.stringify(body)})
  let data=null;try{data=await r.json()}catch{};if(!r.ok)throw new Error(data?.message||data?.hint||data?.details||'Não foi possível completar a chamada.');return data
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function css(){if($('isaCallCss'))return;const s=document.createElement('style');s.id='isaCallCss';s.textContent=`
.isa-call-actions{display:flex;gap:7px;margin-left:auto}.isa-call-btn{width:42px;height:42px;border:0;border-radius:14px;background:#fff;box-shadow:0 6px 14px #6d557522;cursor:pointer;font-size:19px}.isa-call-hide{display:none!important}
.isa-call-overlay{position:fixed;inset:0;z-index:12000;background:#201827bb;backdrop-filter:blur(12px);display:grid;place-items:center;padding:16px}.isa-call-card{width:min(760px,96vw);border-radius:30px;background:linear-gradient(145deg,#fffafd,#eee7ff);padding:18px;box-shadow:0 32px 90px #0006}.isa-call-card.video{width:min(960px,98vw);background:#1f1924;padding:12px}.isa-call-top{display:flex;gap:12px;align-items:center;padding:4px 4px 14px}.isa-call-top .grow{flex:1}.isa-call-top h3{margin:0}.isa-call-top p{margin:4px 0 0;color:#88798f}.isa-call-card.video .isa-call-top h3,.isa-call-card.video .isa-call-top p{color:#fff}.isa-call-stage{position:relative;min-height:360px;border-radius:24px;overflow:hidden;background:linear-gradient(145deg,#e8ddff,#ffe7ef);display:grid;place-items:center}.isa-call-card.video .isa-call-stage{min-height:min(66vh,620px);background:#111}.isa-remote-video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.isa-local-video{position:absolute;right:14px;bottom:14px;width:min(28%,210px);aspect-ratio:3/4;object-fit:cover;border-radius:18px;border:3px solid #fff;background:#2f2736;z-index:3}.isa-call-avatar{width:126px;height:126px;border-radius:38px;background:#fff;display:grid;place-items:center;font-size:54px;box-shadow:0 20px 40px #664d771f;animation:isaPulse 1.8s infinite}.isa-call-name{font-size:1.6rem;font-weight:950;color:#5e4d67;margin-top:18px;text-align:center}.isa-call-state{text-align:center;color:#89788f;margin-top:7px;font-weight:700}@keyframes isaPulse{50%{transform:scale(1.04);box-shadow:0 20px 50px #d783b247}}
.isa-call-controls{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;padding-top:14px}.isa-call-control{border:0;border-radius:17px;height:54px;padding:0 16px;background:#fff;color:#57475f;font-weight:900;cursor:pointer}.isa-call-control.danger{background:#ec5d74;color:#fff}.isa-call-card.video .isa-call-control:not(.danger){background:#ffffff22;color:#fff}.isa-call-error{margin-top:12px;padding:12px 14px;border-radius:16px;background:#fff0f3;color:#995267}
.isa-incoming{width:min(430px,94vw);border-radius:30px;background:linear-gradient(145deg,#fff8fc,#eee5ff);padding:27px;text-align:center;box-shadow:0 30px 80px #0005}.isa-incoming .avatar{width:112px;height:112px;border-radius:36px;margin:auto;background:#fff;display:grid;place-items:center;font-size:49px;animation:isaPulse 1.5s infinite}.isa-incoming h2{margin:18px 0 5px;color:#5c4c65}.isa-incoming p{margin:0;color:#897990}.isa-incoming-actions{display:flex;gap:12px;margin-top:24px}.isa-incoming-actions button{flex:1;border:0;border-radius:18px;padding:15px;font-weight:950;cursor:pointer}.isa-answer{background:#64cf97}.isa-decline{background:#ffdce4;color:#9b4356}
@media(max-width:620px){.isa-call-btn{width:38px;height:38px}.isa-call-card.video{width:100vw;height:100dvh;border-radius:0}.isa-call-card.video .isa-call-stage{min-height:calc(100dvh - 150px)}}`;document.head.appendChild(s)}
function ready(){if(document.hidden)return false;return extMode?!!$('friendChat')&&!$('friendChat').classList.contains('hidden'):!!$('mainView')&&!$('mainView').classList.contains('hidden')&&!!getAuth()}
function conv(){if(extMode)return document.querySelector('#friendConversationList [data-friend-conv].active')?.dataset.friendConv||lastClicked;return document.querySelector('#chatList [data-conv].active')?.dataset.conv||lastClicked}
function initials(n=''){const p=String(n).trim().split(/\s+/);return (p[0]?.[0]||'💜')+(p[1]?.[0]||'')}
function headerBtns(){css();const h=extMode?document.querySelector('.friend-thread-head'):document.querySelector('#chatPanel .chat-header');if(!h)return;let b=$('isaCallActions');if(!b){b=document.createElement('div');b.id='isaCallActions';b.className='isa-call-actions isa-call-hide';b.innerHTML='<button id="isaVoiceCall" class="isa-call-btn" title="Chamada de voz">📞</button><button id="isaVideoCall" class="isa-call-btn" title="Videochamada">🎥</button>';h.appendChild(b);$('isaVoiceCall').onclick=()=>startOut('voice');$('isaVideoCall').onclick=()=>startOut('video')}return b}
async function refreshBtns(){const b=headerBtns();if(!b)return;currentConv=conv();if(!currentConv){b.classList.add('isa-call-hide');return}try{currentCtx=await rpc('live_call_context',{p_conversation_id:currentConv});if(!currentCtx?.eligible){b.classList.add('isa-call-hide');return}b.classList.remove('isa-call-hide');$('isaVoiceCall').classList.toggle('isa-call-hide',!currentCtx.voice);$('isaVideoCall').classList.toggle('isa-call-hide',!currentCtx.video)}catch{b.classList.add('isa-call-hide')}}
function wire(){const root=extMode?$('friendConversationList'):$('chatList');if(root&&!root.dataset.callManagerBound){root.dataset.callManagerBound='1';root.addEventListener('click',e=>{const b=e.target.closest(extMode?'[data-friend-conv]':'[data-conv]');if(!b)return;lastClicked=extMode?b.dataset.friendConv:b.dataset.conv;setTimeout(refreshBtns,180)},true)}if(extMode&&$('friendBackBtn')&&!$('friendBackBtn').dataset.callManagerBound){$('friendBackBtn').dataset.callManagerBound='1';$('friendBackBtn').addEventListener('click',()=>{lastClicked=null;setTimeout(refreshBtns,80)})}}
function status(t){if($('isaCallStatus'))$('isaCallStatus').textContent=t;if($('isaVoiceStatus'))$('isaVoiceStatus').textContent=t}
function err(t){const e=$('isaCallError');if(e){e.textContent=t;e.classList.remove('isa-call-hide')}}
function stopRing(){try{ringStop?.()}catch{};ringStop=null}
function ring(){stopRing();let st=false,t=null,a=null;try{a=new (window.AudioContext||window.webkitAudioContext)()}catch{};const beep=()=>{if(st||!a)return;try{const o=a.createOscillator(),g=a.createGain();o.frequency.value=660;g.gain.setValueAtTime(.0001,a.currentTime);g.gain.exponentialRampToValueAtTime(.1,a.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.35);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.36)}catch{}};beep();t=setInterval(beep,1400);ringStop=()=>{st=true;clearInterval(t);try{a?.close()}catch{}}}
function callUi(kind,name,st){css();$('isaActiveCall')?.remove();const r=document.createElement('div');r.id='isaActiveCall';r.className='isa-call-overlay';r.innerHTML=`<section class="isa-call-card ${kind==='video'?'video':''}"><header class="isa-call-top"><div class="grow"><h3>${esc(name)}</h3><p id="isaCallStatus">${esc(st)}</p></div></header><div class="isa-call-stage">${kind==='video'?'<video id="isaRemoteVideo" class="isa-remote-video" autoplay playsinline></video><video id="isaLocalVideo" class="isa-local-video" autoplay muted playsinline></video>':`<div><div class="isa-call-avatar">${esc(initials(name))}</div><div class="isa-call-name">${esc(name)}</div><div id="isaVoiceStatus" class="isa-call-state">${esc(st)}</div><audio id="isaRemoteAudio" autoplay></audio></div>`}</div><div class="isa-call-controls"><button id="isaMute" class="isa-call-control">🎙️ Mudo</button>${kind==='video'?'<button id="isaCam" class="isa-call-control">📷 Câmera</button><button id="isaSwitch" class="isa-call-control">🔄 Trocar</button>':''}<button id="isaHang" class="isa-call-control danger">📞 Desligar</button></div><div id="isaCallError" class="isa-call-error isa-call-hide"></div></section>`;document.body.appendChild(r);$('isaHang').onclick=()=>endCall(true);$('isaMute').onclick=mute;$('isaCam')?.addEventListener('click',camera);$('isaSwitch')?.addEventListener('click',switchCam)}
function incomingUi(c){css();$('isaIncomingCall')?.remove();incoming=c.id;ring();const r=document.createElement('div');r.id='isaIncomingCall';r.className='isa-call-overlay';r.innerHTML=`<section class="isa-incoming"><div class="avatar">${c.kind==='video'?'🎥':'📞'}</div><h2>${esc(c.callerName||'Família')} está ligando</h2><p>${c.kind==='video'?'Videochamada':'Chamada de voz'}</p><div class="isa-incoming-actions"><button class="isa-decline">Recusar</button><button class="isa-answer">Atender</button></div></section>`;document.body.appendChild(r);r.querySelector('.isa-decline').onclick=async()=>{stopRing();try{await rpc('live_call_decline',{p_call_id:c.id})}catch{};r.remove();incoming=null};r.querySelector('.isa-answer').onclick=async()=>{stopRing();r.remove();incoming=null;await accept(c)}}
function mediaMessage(e,kind){const n=e?.name||'',m=String(e?.message||'').toLowerCase();if(n==='NotAllowedError'||n==='PermissionDeniedError'||m.includes('permission denied'))return kind==='video'?'O Windows ou o navegador bloqueou câmera/microfone. Libere as permissões e tente novamente.':'O Windows ou o navegador bloqueou o microfone. Libere a permissão e tente novamente.';if(n==='NotFoundError'||n==='DevicesNotFoundError')return kind==='video'?'Câmera ou microfone não encontrado.':'Nenhum microfone foi encontrado.';if(n==='NotReadableError'||n==='TrackStartError')return kind==='video'?'Câmera ou microfone está sendo usado por outro aplicativo.':'O microfone está sendo usado por outro aplicativo.';return kind==='video'?'Não foi possível abrir câmera e microfone.':'Não foi possível abrir o microfone.'}
async function media(kind){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Este navegador não oferece chamadas.');try{return await navigator.mediaDevices.getUserMedia(kind==='video'?{audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:{facingMode:{ideal:'user'},width:{ideal:1280},height:{ideal:720}}}:{audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false})}catch(e){throw new Error(mediaMessage(e,kind))}}
function pc(){return new RTCPeerConnection({iceCandidatePoolSize:6,iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']},{urls:'stun:stun.cloudflare.com:3478'}]})}
function restartPeer(c){if(!c||c.ended||c.restartBusy)return;c.restartBusy=true;try{c.pc.restartIce?.();status('Reconectando…')}catch{}setTimeout(()=>{if(c)c.restartBusy=false},1800)}
function attach(c){c.pc.ontrack=e=>{const s=e.streams?.[0]||new MediaStream([e.track]);if(c.kind==='video'&&$('isaRemoteVideo')){$('isaRemoteVideo').srcObject=s;$('isaRemoteVideo').play().catch(()=>{})}else if($('isaRemoteAudio')){$('isaRemoteAudio').srcObject=s;$('isaRemoteAudio').play().catch(()=>{})}};c.pc.onicecandidate=e=>{if(e.candidate)rpc('live_call_add_ice',{p_call_id:c.id,p_candidate:e.candidate.toJSON?e.candidate.toJSON():e.candidate}).catch(()=>{})};c.pc.onconnectionstatechange=()=>{const s=c.pc.connectionState;if(s==='connected'){c.connected=true;c.restartBusy=false;status('Conectada 💜')}else if(s==='connecting')status('Conectando…');else if(s==='disconnected'){status('Reconectando…');setTimeout(()=>{if(active===c&&c.pc.connectionState==='disconnected')restartPeer(c)},1200)}else if(s==='failed'){if(!c.restartAttempted){c.restartAttempted=true;restartPeer(c);setTimeout(()=>{if(active===c&&c.pc.connectionState==='failed'){status('Falha na conexão');err('A rede não conseguiu criar uma conexão direta. Tente novamente ou troque de rede.')}},3000)}else{status('Falha na conexão');err('Não foi possível manter a conexão.')}}};c.pc.oniceconnectionstatechange=()=>{if(c.pc.iceConnectionState==='failed')restartPeer(c)}}
function local(stream,kind){if(kind==='video'&&$('isaLocalVideo')){$('isaLocalVideo').srcObject=stream;$('isaLocalVideo').play().catch(()=>{})}}
async function buildCaller(rec,kind,name){callUi(kind,name,'Ligando…');const stream=await media(kind),peer=pc();active={id:rec.id,kind,name,stream,pc:peer,caller:true,last:0,remote:false,connected:false,timer:null,timeout:null,ended:false,restartBusy:false,restartAttempted:false};local(stream,kind);stream.getTracks().forEach(t=>peer.addTrack(t,stream));attach(active);const offer=await peer.createOffer();await peer.setLocalDescription(offer);await rpc('live_call_set_offer',{p_call_id:rec.id,p_offer:peer.localDescription.toJSON?peer.localDescription.toJSON():peer.localDescription});signal();active.timeout=setTimeout(()=>{if(active&&!active.connected){status('Não atendida');endCall(true)}},45000)}
async function startOut(kind){if(active)return;const c=conv();if(!c)return;try{const ctx=currentCtx?.peerName?currentCtx:await rpc('live_call_context',{p_conversation_id:c});if(!ctx?.eligible||!ctx?.[kind])throw new Error('Esta chamada não está disponível para este contato.');const rec=await rpc('live_call_start',{p_conversation_id:c,p_kind:kind});try{await buildCaller(rec,kind,ctx.peerName||rec.peerName)}catch(e){try{await rpc('live_call_end',{p_call_id:rec.id})}catch{};clean();throw e}}catch(e){alert(e.message||'Não foi possível iniciar a chamada.')}}
async function accept(c){if(active)return;try{callUi(c.kind,c.callerName||c.peerName,'Atendendo…');const stream=await media(c.kind),peer=pc();active={id:c.id,kind:c.kind,name:c.callerName||c.peerName,stream,pc:peer,caller:false,last:0,remote:true,connected:false,timer:null,timeout:null,ended:false,restartBusy:false,restartAttempted:false};local(stream,c.kind);stream.getTracks().forEach(t=>peer.addTrack(t,stream));attach(active);await peer.setRemoteDescription(new RTCSessionDescription(c.offer));const ans=await peer.createAnswer();await peer.setLocalDescription(ans);await rpc('live_call_answer',{p_call_id:c.id,p_answer:peer.localDescription.toJSON?peer.localDescription.toJSON():peer.localDescription});signal();status('Conectando…')}catch(e){err(e.message||'Não foi possível atender.');try{await rpc('live_call_decline',{p_call_id:c.id})}catch{};setTimeout(clean,1800)}}
function signal(){if(!active)return;clearInterval(active.timer);const tick=async()=>{const c=active;if(!c||c.ended)return;try{const r=await rpc('live_call_poll_ice',{p_call_id:c.id,p_after:c.last||0});if(!active||active.id!==c.id)return;c.last=Number(r?.lastId||c.last||0);for(const i of(r?.items||[])){try{await c.pc.addIceCandidate(new RTCIceCandidate(i.candidate))}catch{}}if(c.caller&&!c.remote&&r?.state==='accepted'&&r?.answer){await c.pc.setRemoteDescription(new RTCSessionDescription(r.answer));c.remote=true;status('Conectando…')}if(['declined','missed','ended','gone'].includes(r?.state)){status(r.state==='declined'?'Chamada recusada':r.state==='missed'?'Não atendida':'Chamada encerrada');setTimeout(()=>endCall(false),800)}}catch{}};tick();active.timer=setInterval(tick,900)}
function mute(){if(!active)return;const tr=active.stream?.getAudioTracks()||[],on=tr.some(t=>t.enabled);tr.forEach(t=>t.enabled=!on);$('isaMute').textContent=on?'🔇 Ativar mic':'🎙️ Mudo'}
function camera(){if(!active||active.kind!=='video')return;const tr=active.stream?.getVideoTracks()||[],on=tr.some(t=>t.enabled);tr.forEach(t=>t.enabled=!on);$('isaCam').textContent=on?'🚫 Ativar câmera':'📷 Câmera'}
async function switchCam(){if(!active||active.kind!=='video')return;try{const ds=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput');if(ds.length<2)return;const old=active.stream.getVideoTracks()[0],id=old?.getSettings?.().deviceId,idx=Math.max(0,ds.findIndex(d=>d.deviceId===id)),next=ds[(idx+1)%ds.length],s=await navigator.mediaDevices.getUserMedia({video:{deviceId:{exact:next.deviceId}},audio:false}),nt=s.getVideoTracks()[0],sender=active.pc.getSenders().find(x=>x.track?.kind==='video');await sender?.replaceTrack(nt);old?.stop();if(old)active.stream.removeTrack(old);active.stream.addTrack(nt);local(active.stream,'video')}catch{err('Não foi possível trocar a câmera.')}}
function clean(){stopRing();$('isaIncomingCall')?.remove();$('isaActiveCall')?.remove();incoming=null;if(active){clearInterval(active.timer);clearTimeout(active.timeout);try{active.pc?.close()}catch{};try{active.stream?.getTracks().forEach(t=>t.stop())}catch{};active=null}}
async function endCall(send=true){const c=active;if(!c){clean();return}c.ended=true;clearInterval(c.timer);clearTimeout(c.timeout);if(send){try{await rpc('live_call_end',{p_call_id:c.id})}catch{}}clean()}
async function poll(){if(!ready())return;try{const rows=await rpc('live_call_poll')||[];if(active){const own=rows.find(x=>x.id===active.id);if(own&&['declined','missed','ended'].includes(own.state)){status(own.state==='declined'?'Chamada recusada':own.state==='missed'?'Não atendida':'Chamada encerrada');setTimeout(()=>endCall(false),800)}return}const inc=rows.find(x=>x.incoming&&x.state==='ringing'&&x.offer);if(inc&&!incoming)incomingUi(inc);if(incoming&&!rows.some(x=>x.id===incoming&&x.state==='ringing')){stopRing();$('isaIncomingCall')?.remove();incoming=null}}catch{}}
function start(){css();headerBtns();wire();setTimeout(refreshBtns,500);setTimeout(refreshBtns,1500);clearInterval(pollTimer);pollTimer=setInterval(poll,2500);setTimeout(poll,700);document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshBtns();poll()}});window.addEventListener('online',()=>{if(active)restartPeer(active);poll()});window.addEventListener('pagehide',()=>{if(active)rpc('live_call_end',{p_call_id:active.id}).catch(()=>{});clean()})}
start()
