import { CONFIG } from './config.js'
const $=id=>document.getElementById(id)
let loading=false
function sessionToken(){try{const ref=new URL(CONFIG.SUPABASE_URL).hostname.split('.')[0],raw=localStorage.getItem(`sb-${ref}-auth-token`);if(!raw)return null;const d=JSON.parse(raw);return d?.access_token||d?.currentSession?.access_token||d?.session?.access_token||null}catch{return null}}
async function rpc(name,args={}){const token=sessionToken();if(!token)throw new Error('Sem sessão');const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(args),cache:'no-store'});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.message||'Não foi possível consultar o diário.');return d}
async function alerts(){const token=sessionToken();if(!token)return[];const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/parental_alerts?select=id,title,body,severity,created_at,read_at,source_id&alert_type=eq.diary_safety&order=created_at.desc&limit=5`,{headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)return[];return r.json()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function mount(){const panel=$('supervisionPanel');if(!panel||$('diarySupervisionBox'))return $('diarySupervisionBox');const box=document.createElement('section');box.id='diarySupervisionBox';box.style.cssText='margin:16px 0;padding:16px;border-radius:22px;background:linear-gradient(145deg,#f5edff,#fff0f7);box-shadow:0 8px 22px rgba(90,68,110,.08)';box.innerHTML='<div style="display:flex;gap:10px;align-items:center"><div style="font-size:30px">📔</div><div><strong>Meu Diário • proteção</strong><small style="display:block;color:#8d8197">Estado de segurança do diário da Isa</small></div></div><div id="diaryParentState" style="margin-top:12px;color:#7b6a86">Verificando…</div><div id="diaryParentAlerts"></div>';const info=panel.querySelector('.supervision-info');if(info?.nextSibling)panel.insertBefore(box,info.nextSibling);else panel.prepend(box);return box}
async function load(){if(loading)return;const box=mount();if(!box)return;loading=true;try{const s=await rpc('diary_status',{});if(s.mode!=='parent'){box.classList.add('hidden');return}box.classList.remove('hidden');const state=$('diaryParentState');if(!s.configured){state.innerHTML='A Isa ainda não criou o diário.';return}if(s.parentalUnlocked)state.innerHTML='<div style="padding:11px 12px;border-radius:15px;background:#fff3bf;font-weight:900">🔓 Acesso parental de segurança liberado</div><button id="openDiarySafetyBtn" class="soft-btn" style="margin-top:9px" type="button">Abrir diário por segurança</button>';else state.innerHTML='<div style="padding:11px 12px;border-radius:15px;background:#e7f6ec">🔒 Diário protegido • sem acesso parental liberado</div>';$('openDiarySafetyBtn')?.addEventListener('click',()=>window.open('./diario.html?parent=1','_blank','noopener'));const a=await alerts();$('diaryParentAlerts').innerHTML=a.length?'<h4 style="margin:14px 0 7px">Alertas do Diário</h4>'+a.map(x=>`<article style="padding:10px 11px;margin:7px 0;border-radius:14px;background:#fff"><strong>${esc(x.title)}</strong><p style="margin:4px 0;font-size:.8rem">${esc(x.body||'')}</p><small style="color:#95889b">${new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(x.created_at))}</small></article>`).join(''):''}catch{box.classList.add('hidden')}finally{loading=false}}
mount();load()
