const $=id=>document.getElementById(id)
const norm=v=>String(v||'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'')
function currentName(){return norm(window.__ISA_FRIEND_PERSON__?.name||$('friendName')?.textContent)}
function isPaloma(){return currentName()==='paloma'}
function addStyle(){if($('externalMenuStyle'))return;const s=document.createElement('style');s.id='externalMenuStyle';s.textContent=`
.family-primary-nav{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(72px,1fr));gap:8px!important;margin:8px 0 12px!important;position:relative!important;z-index:80!important;pointer-events:auto!important}.family-primary-tab{min-width:0!important;min-height:50px!important;padding:7px 6px!important;border:1px solid rgba(255,255,255,.9)!important;border-radius:16px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:5px!important;font-weight:900!important;cursor:pointer!important;pointer-events:auto!important;box-shadow:0 5px 0 rgba(163,139,189,.13),0 9px 16px rgba(93,70,110,.08)!important}.family-primary-tab:nth-child(5n+1){background:linear-gradient(145deg,#fff4f9,#f7d9e8)!important}.family-primary-tab:nth-child(5n+2){background:linear-gradient(145deg,#f1eaff,#dfd5ff)!important}.family-primary-tab:nth-child(5n+3){background:linear-gradient(145deg,#ecf7ff,#d6eaf8)!important}.family-primary-tab:nth-child(5n+4){background:linear-gradient(145deg,#f0fbf2,#d8eedc)!important}.family-primary-tab:nth-child(5n){background:linear-gradient(145deg,#fff9df,#f5e7ae)!important}.family-primary-tab span{font-size:10px!important;white-space:nowrap!important}.family-primary-tab.icon-only{font-size:20px!important}.family-primary-tab.icon-only span{display:none!important}.friend-profile .pss-profile-edit{display:none!important}.friend-composer #pssStickerBtn{display:none!important}
@media(max-width:780px){.family-primary-nav{position:sticky!important;top:0!important;grid-template-columns:repeat(4,minmax(0,1fr));padding:6px!important;margin:4px 0 8px!important;border-radius:17px;background:rgba(255,250,255,.94)!important;backdrop-filter:blur(12px);z-index:95!important}.family-primary-tab{min-height:46px!important;padding:4px 2px!important}.family-primary-tab span{font-size:8px!important}.family-primary-tab.icon-only{font-size:19px!important}}
`;document.head.appendChild(s)}
function setHtml(el,html){if(el&&el.innerHTML!==html)el.innerHTML=html}
function stableOrder(nav,items){const order=items.filter(Boolean),wanted=new Set(order),current=[...nav.children].filter(el=>wanted.has(el));if(current.length===order.length&&current.every((el,i)=>el===order[i]))return;order.forEach(el=>{if(el.parentNode===nav)nav.appendChild(el)})}
function ensure(){addStyle();const nav=document.querySelector('.family-primary-nav');if(!nav)return false;const chat=$('friendChatsTab');if(chat){chat.disabled=false;chat.removeAttribute('aria-disabled');chat.classList.remove('is-locked');chat.classList.add('family-primary-tab');setHtml(chat,'💬 <span>Chat</span>')}
let social=$('friendSocialBtn');if(!social){social=document.createElement('button');social.id='friendSocialBtn';social.type='button';nav.appendChild(social)}social.classList.add('family-primary-tab');social.classList.remove('is-locked');social.disabled=false;social.removeAttribute('aria-disabled');setHtml(social,'🌸 <span>Nossa Rede</span>')
let games=$('friendGamesMenuBtn');if(!games){games=document.createElement('button');games.id='friendGamesMenuBtn';games.type='button';nav.appendChild(games)}games.classList.add('family-primary-tab');setHtml(games,'🎮 <span>Joguinhos</span>')
let studies=$('friendStudiesMenuBtn');if(isPaloma()){if(!studies){studies=document.createElement('button');studies.id='friendStudiesMenuBtn';studies.type='button';nav.appendChild(studies)}studies.classList.add('family-primary-tab');studies.classList.remove('hidden');studies.style.removeProperty('display');setHtml(studies,'🩺 <span>Estudos</span>')}else if(studies){studies.classList.add('hidden');studies.style.setProperty('display','none','important')}
let settings=$('friendSettingsBtn');if(!settings){settings=document.createElement('button');settings.id='friendSettingsBtn';settings.type='button';nav.appendChild(settings)}settings.classList.add('family-primary-tab','icon-only','friend-settings-menu');settings.classList.remove('hidden');settings.textContent='⚙️';settings.title='Configurações';settings.setAttribute('aria-label','Configurações');settings.style.removeProperty('display')
$('friendProfileMenuBtn')?.remove();$('friendStickerMenuBtn')?.remove();document.querySelectorAll('.friend-profile .pss-profile-edit').forEach(b=>b.style.setProperty('display','none','important'));stableOrder(nav,[chat,social,games,isPaloma()?studies:null,settings]);return true}
window.__ISA_ENSURE_EXTERNAL_MENU__=ensure
ensure();document.addEventListener('isa:friend-portal-entered',ensure);document.addEventListener('isa:friend-access-valid',ensure);let tries=0;const timer=setInterval(()=>{ensure();if(++tries>36)clearInterval(timer)},350)
