const GAMES={
  bricks:{title:'🧱 Bricks Pastel',url:'./jogos/bricks-pastel.html?v=3-mobile',desc:'Quebre os tijolos coloridos e continue jogando mesmo depois de limpar a tela.'},
  tetris:{title:'🧩 Tetris Pastel',url:'./jogos/tetris-pastel.html?v=2-mobile',desc:'Monte linhas com blocos coloridos em uma versão pastel e 3D.'},
  bubbles:{title:'🫧 Bubble Shooter Pastel',url:'./jogos/bubble-shooter-pastel.html?v=2-mobile',desc:'Mire, combine cores e estoure grupos de bolhas.'}
}
const $=id=>document.getElementById(id)
const norm=v=>String(v||'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'')
const mobileContext=new URLSearchParams(location.search).get('mobile')==='1'||/acesso-mobile\.html$/i.test(location.pathname)||matchMedia('(max-width:700px)').matches
function currentName(){const main=norm($('myName')?.textContent);if(main&&main!=='família')return main;const external=norm($('friendName')?.textContent);if(external&&external!=='perfil')return external;return''}
function eligible(){const n=currentName();return['isa','keise','alan','paloma','elion','vania','davi'].includes(n)}
function isExternal(){return!!$('friendApp')}
function injectStyles(){
  if($('cantinhoGamesStyles'))return
  const s=document.createElement('style');s.id='cantinhoGamesStyles';s.textContent=`
  html.cantinho-game-open,html.cantinho-game-open body{overflow:hidden!important;overscroll-behavior:none!important}
  .cantinho-games-overlay{position:fixed;inset:0;z-index:2147482000;background:rgba(43,31,70,.58);backdrop-filter:blur(10px);display:grid;place-items:center;padding:18px}.cantinho-games-overlay.hidden{display:none!important}
  .cantinho-games-shell{width:min(1120px,96vw);height:min(820px,94dvh);background:linear-gradient(145deg,#fffdf8,#fff1fa 52%,#f1ecff);border:2px solid rgba(255,255,255,.95);border-radius:28px;box-shadow:0 24px 70px rgba(51,37,94,.32);overflow:hidden;display:flex;flex-direction:column;color:#44316f}
  .cantinho-games-head{display:flex;align-items:center;gap:10px;padding:14px 16px;background:rgba(255,255,255,.86);border-bottom:1px solid #eadff3;flex:0 0 auto}.cantinho-games-head strong{font-size:18px;flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cantinho-games-close,.cantinho-games-back{border:0;border-radius:14px;min-width:42px;height:42px;background:#fff;box-shadow:0 5px 14px #6b4a8b22;cursor:pointer;font-weight:900;color:#59417d;touch-action:manipulation}.cantinho-games-back.hidden{display:none!important}
  .cantinho-games-hub{padding:22px;overflow:auto;flex:1;-webkit-overflow-scrolling:touch}.cantinho-games-intro{text-align:center;margin:4px auto 20px;max-width:620px}.cantinho-games-intro h2{margin:0 0 7px;font-size:clamp(26px,4vw,42px);color:#6d48ac}.cantinho-games-intro p{margin:0;color:#7a6a8d;font-weight:700}.cantinho-games-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,300px));gap:18px;justify-content:center}
  .cantinho-game-card{border:2px solid #fff;background:linear-gradient(145deg,#fff,#fff3fb);border-radius:24px;padding:18px;box-shadow:0 12px 28px #6a438d25;cursor:pointer;text-align:left;color:#44316f;transition:transform .18s ease,box-shadow .18s ease;touch-action:manipulation}.cantinho-game-card:hover{transform:translateY(-3px);box-shadow:0 16px 34px #6a438d34}.cantinho-game-card h3{margin:0 0 5px;font-size:21px}.cantinho-game-card p{margin:0;color:#806f91;font-weight:650;line-height:1.35}
  .cantinho-game-art{height:150px;border-radius:19px;background:linear-gradient(145deg,#211b59,#352d78);margin-bottom:14px;overflow:hidden;position:relative}.art-bricks{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;padding:22px}.art-bricks span{border:2px solid #fff;border-radius:7px;box-shadow:inset 0 5px #fff4,inset 0 -6px #0002}.art-bricks span:nth-child(5n+1){background:#ef72a8}.art-bricks span:nth-child(5n+2){background:#72b4e9}.art-bricks span:nth-child(5n+3){background:#a86bdc}.art-bricks span:nth-child(5n+4){background:#83cf7d}.art-bricks span:nth-child(5n){background:#f4bc35}
  .art-tetris{display:grid;grid-template-columns:repeat(6,1fr);grid-template-rows:repeat(5,1fr);gap:4px;padding:18px}.art-tetris span{border:2px solid #fff;border-radius:6px;box-shadow:inset 0 4px #fff4,inset 0 -5px #0002}.art-tetris span:nth-child(1),.art-tetris span:nth-child(2),.art-tetris span:nth-child(8),.art-tetris span:nth-child(9){background:#a86bdc}.art-tetris span:nth-child(4),.art-tetris span:nth-child(10),.art-tetris span:nth-child(16),.art-tetris span:nth-child(22){background:#72b4e9}.art-tetris span:nth-child(19),.art-tetris span:nth-child(20),.art-tetris span:nth-child(21),.art-tetris span:nth-child(27){background:#ef72a8}.art-tetris span:nth-child(25),.art-tetris span:nth-child(26),.art-tetris span:nth-child(31),.art-tetris span:nth-child(32){background:#83cf7d}.art-tetris span:not([style]){min-width:0}
  .art-bubbles{padding:15px}.art-bubbles span{position:absolute;width:31px;height:31px;border-radius:50%;border:2px solid #fff;box-shadow:inset 0 7px #fff6,inset 0 -7px #0002}.art-bubbles span:nth-child(6n+1){background:#ef72a8}.art-bubbles span:nth-child(6n+2){background:#72b4e9}.art-bubbles span:nth-child(6n+3){background:#a86bdc}.art-bubbles span:nth-child(6n+4){background:#83cf7d}.art-bubbles span:nth-child(6n+5){background:#f4bc35}.art-bubbles span:nth-child(6n){background:#81d8d0}
  .cantinho-game-frame-wrap{flex:1;min-height:0;overflow:hidden;background:#e9e3ff}.cantinho-game-frame-wrap.hidden{display:none!important}.cantinho-game-frame{width:100%;height:100%;border:0;background:#e9e3ff;display:block;touch-action:auto}
  .cantinho-games-popwrap{position:relative;display:flex;align-items:center}.cantinho-games-pop{position:absolute;left:0;bottom:calc(100% + 9px);z-index:9999;min-width:170px;padding:7px;background:#fff;border:1px solid #eadff3;border-radius:15px;box-shadow:0 12px 28px #4d366b2e}.cantinho-games-pop.hidden{display:none!important}.cantinho-games-pop button{width:100%;border:0;background:transparent;border-radius:10px;padding:10px 12px;text-align:left;cursor:pointer;font-weight:800;color:#4f3a72}.cantinho-games-pop button:hover{background:#f5efff}
  @media(max-width:700px){.cantinho-games-overlay{padding:0;background:#f4ecfb;backdrop-filter:none}.cantinho-games-shell{width:100vw;height:100dvh;max-height:none;border-radius:0;border:0}.cantinho-games-head{padding:8px 10px;padding-top:max(8px,env(safe-area-inset-top));min-height:54px}.cantinho-games-head strong{font-size:16px}.cantinho-games-close,.cantinho-games-back{min-width:40px;height:40px;border-radius:12px}.cantinho-games-hub{padding:12px 14px max(18px,env(safe-area-inset-bottom))}.cantinho-games-intro{margin:2px auto 12px}.cantinho-games-intro h2{font-size:28px}.cantinho-games-intro p{font-size:13px}.cantinho-games-grid{grid-template-columns:1fr;gap:12px}.cantinho-game-card{max-width:430px;width:100%;justify-self:center;padding:12px;border-radius:19px;display:grid;grid-template-columns:104px 1fr;grid-template-rows:auto auto;column-gap:12px;align-items:center}.cantinho-game-art{height:92px;width:104px;margin:0;grid-row:1/3}.cantinho-game-card h3{font-size:18px;align-self:end}.cantinho-game-card p{font-size:12px;align-self:start}.art-bricks{padding:12px;gap:4px}.art-tetris{padding:10px;gap:3px}.art-bubbles span{width:23px;height:23px}.cantinho-game-frame-wrap{overscroll-behavior:none}}
  `;document.head.appendChild(s)
}
function bubblesArt(){return Array.from({length:18},(_,i)=>`<span style="left:${18+(i%6)*15}%;top:${12+Math.floor(i/6)*27+(i%2)*7}px"></span>`).join('')}
function mobileCSSFor(key){
  const common=`
  html,body{width:100%!important;max-width:100%!important;overflow-x:hidden!important;overscroll-behavior:none!important}body{min-height:100dvh!important}.app{max-width:none!important;padding:7px!important}.top{grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:6px!important;margin-bottom:7px!important}.brand{grid-column:1/-1!important;text-align:center!important;min-height:46px!important}.brand .m,.brand .d{font-size:clamp(25px,8vw,33px)!important;line-height:.95!important;display:inline!important;letter-spacing:-1px!important}.brand .d{margin-left:5px!important}.ribbon,.spark{display:none!important}.stat,.restart{min-height:48px!important;padding:5px 4px!important;border-radius:12px!important;font-size:11px!important}.small{font-size:8px!important}.count{font-size:17px!important}.bottom{display:none!important}`
  if(key==='bricks')return common+`
  .layout{display:block!important}.side{display:none!important}.board{width:100%!important;height:min(66dvh,510px)!important;min-height:360px!important;aspect-ratio:auto!important;border-radius:17px!important}.bricks{padding:4% 2.5% 0!important;gap:2% .7%!important}.brick{font-size:clamp(12px,4vw,19px)!important;border-width:2px!important}.restart{font-size:10px!important}`
  if(key==='tetris')return common+`
  .layout{display:flex!important;flex-direction:column!important;gap:6px!important}.boardWrap{width:100%!important}.board{width:min(56vw,230px,29dvh)!important;min-width:170px!important;border-radius:16px!important}.side{padding:6px!important;gap:5px!important;border-radius:14px!important;background:transparent!important;border:0!important;box-shadow:none!important}.side .panel:first-child,.side .help{display:none!important}.side .panel{padding:6px 8px!important;border-radius:12px!important}.side .panel h2{font-size:15px!important;margin:0!important}.status{font-size:11px!important;min-height:18px!important}.controls{width:min(100%,430px)!important;margin:0 auto!important;gap:5px!important}.ctrl{padding:10px 6px!important;border-radius:12px!important;font-size:18px!important}.ctrl.big{font-size:13px!important;padding:9px!important}.restart{font-size:10px!important}`
  return common+`
  .layout{display:block!important}.board{width:100%!important;height:min(62dvh,500px)!important;min-height:350px!important;aspect-ratio:auto!important;border-radius:17px!important}.side{margin-top:6px!important;padding:5px!important;gap:4px!important;border-radius:13px!important}.side .help,.side .panel:last-child{display:none!important}.side .panel:first-child{padding:5px 8px!important;border-radius:11px!important;display:grid!important;grid-template-columns:auto 44px 1fr!important;align-items:center!important;gap:7px!important;text-align:left!important}.side .panel:first-child h2{font-size:13px!important;margin:0!important}.nextBubble{width:38px!important;height:38px!important;margin:0!important;border-width:3px!important}.status{font-size:10px!important;min-height:0!important}.restart{font-size:10px!important}`
}
function prepareMobileFrame(frame,key){
  if(!mobileContext)return
  try{
    const doc=frame.contentDocument;if(!doc||!doc.head)return
    let style=doc.getElementById('cantinhoEmbeddedMobileStyle');if(!style){style=doc.createElement('style');style.id='cantinhoEmbeddedMobileStyle';doc.head.appendChild(style)}
    style.textContent=mobileCSSFor(key)
    doc.documentElement.dataset.cantinhoMobile='1'
    setTimeout(()=>{try{frame.contentWindow?.dispatchEvent(new Event('resize'))}catch{}},60)
    setTimeout(()=>{try{frame.contentWindow?.dispatchEvent(new Event('resize'))}catch{}},260)
  }catch(error){console.warn('Ajuste mobile do joguinho:',error)}
}
function ensureOverlay(){
  injectStyles();let overlay=$('cantinhoGamesOverlay');if(overlay)return overlay
  overlay=document.createElement('div');overlay.id='cantinhoGamesOverlay';overlay.className='cantinho-games-overlay hidden';overlay.innerHTML=`<section class="cantinho-games-shell" role="dialog" aria-modal="true" aria-label="Joguinhos"><header class="cantinho-games-head"><button id="cantinhoGamesBack" class="cantinho-games-back hidden" type="button">←</button><strong id="cantinhoGamesTitle">🎮 Joguinhos</strong><button id="cantinhoGamesClose" class="cantinho-games-close" type="button">✕</button></header><div id="cantinhoGamesHub" class="cantinho-games-hub"><div class="cantinho-games-intro"><h2>Joguinhos ✨</h2><p>Um cantinho só para relaxar e jogar.</p></div><div class="cantinho-games-grid"><button class="cantinho-game-card" data-game="bricks" type="button"><div class="cantinho-game-art art-bricks">${'<span></span>'.repeat(12)}</div><h3>${GAMES.bricks.title}</h3><p>${GAMES.bricks.desc}</p></button><button class="cantinho-game-card" data-game="tetris" type="button"><div class="cantinho-game-art art-tetris">${'<span></span>'.repeat(36)}</div><h3>${GAMES.tetris.title}</h3><p>${GAMES.tetris.desc}</p></button><button class="cantinho-game-card" data-game="bubbles" type="button"><div class="cantinho-game-art art-bubbles">${bubblesArt()}</div><h3>${GAMES.bubbles.title}</h3><p>${GAMES.bubbles.desc}</p></button></div></div><div id="cantinhoGameFrameWrap" class="cantinho-game-frame-wrap hidden"><iframe id="cantinhoGameFrame" class="cantinho-game-frame" title="Joguinho" loading="eager"></iframe></div></section>`
  document.body.appendChild(overlay)
  const hub=$('cantinhoGamesHub'),wrap=$('cantinhoGameFrameWrap'),frame=$('cantinhoGameFrame'),back=$('cantinhoGamesBack'),title=$('cantinhoGamesTitle')
  function showHub(){frame.onload=null;frame.src='about:blank';wrap.classList.add('hidden');hub.classList.remove('hidden');back.classList.add('hidden');title.textContent='🎮 Joguinhos'}
  function close(){overlay.classList.add('hidden');document.documentElement.classList.remove('cantinho-game-open');showHub()}
  $('cantinhoGamesClose').onclick=close;back.onclick=showHub
  hub.querySelectorAll('[data-game]').forEach(btn=>btn.onclick=()=>{const key=btn.dataset.game,g=GAMES[key];if(!g)return;hub.classList.add('hidden');wrap.classList.remove('hidden');back.classList.remove('hidden');title.textContent=g.title;frame.title=g.title;frame.onload=()=>prepareMobileFrame(frame,key);frame.src=g.url+(mobileContext?'&embedMobile=1':'')})
  overlay.addEventListener('click',e=>{if(e.target===overlay)close()});window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!overlay.classList.contains('hidden'))close()});return overlay
}
function openGames(){if(!eligible())return;ensureOverlay().classList.remove('hidden');document.documentElement.classList.add('cantinho-game-open')}
window.__CANTINHO_OPEN_GAMES__=openGames
function wireMain(){if(isExternal()||!eligible())return;const plus=$('groupPlusBtn'),menu=$('groupPlusMenu');if(!plus||!menu)return;plus.classList.remove('hidden');if(menu.querySelector('[data-cantinho-games]'))return;const b=document.createElement('button');b.type='button';b.dataset.cantinhoGames='1';b.textContent='🎮 Joguinhos';b.onclick=()=>{menu.classList.add('hidden');openGames()};menu.appendChild(b)}
function wirePaloma(){if(!isExternal()||!eligible())return;const composer=document.querySelector('.friend-composer');if(!composer||$('palomaGamesPlus'))return;const wrap=document.createElement('div');wrap.className='cantinho-games-popwrap';wrap.innerHTML='<button id="palomaGamesPlus" class="emoji-btn" type="button" title="Mais opções">＋</button><div id="palomaGamesPop" class="cantinho-games-pop hidden"><button type="button" data-open-games>🎮 Joguinhos</button></div>';composer.insertBefore(wrap,composer.firstChild);const btn=$('palomaGamesPlus'),pop=$('palomaGamesPop');btn.onclick=e=>{e.stopPropagation();pop.classList.toggle('hidden')};pop.querySelector('[data-open-games]').onclick=()=>{pop.classList.add('hidden');openGames()};document.addEventListener('click',e=>{if(!wrap.contains(e.target))pop.classList.add('hidden')})}
function wire(){if(!eligible())return;ensureOverlay();wireMain();wirePaloma()}
const observer=new MutationObserver(wire);observer.observe(document.body,{childList:true,subtree:true,characterData:true});let tries=0;const timer=setInterval(()=>{wire();if(++tries>120)clearInterval(timer)},500);wire()
