// Isa Chat • Nossa Rede v4 — camada visual/interativa aprovada.
// Não substitui o núcleo social: reorganiza o DOM e preserva publicação, reações, comentários e privacidade existentes.
const STYLE_ID='isaNossaRedeV4Css';
const qs=(root,sel)=>root?.querySelector?.(sel)||null;
const qsa=(root,sel)=>[...(root?.querySelectorAll?.(sel)||[])];
function addCss(){if(document.getElementById(STYLE_ID))return;const l=document.createElement('link');l.id=STYLE_ID;l.rel='stylesheet';l.href='./nossa-rede-v4.css?v=1-approved';document.head.appendChild(l)}
function toast(root,text){const el=document.getElementById(root.id==='familySocialOverlay'?'friendToast':'toast');if(el){el.textContent=text;el.classList.remove('hidden');clearTimeout(el._nr4);el._nr4=setTimeout(()=>el.classList.add('hidden'),2800)}else console.info(text)}
function external(root){return root?.id==='familySocialOverlay'}
function ids(root){return external(root)?{caption:'fsCaption',media:'fsMedia',publish:'fsPublish',edit:'fsEditProfile',status:'fsStatusStrip',family:'fsFamilyList'}:{caption:'socialCaption',media:'socialMediaInput',publish:'socialPublish',edit:'socialEditProfile',status:'socialStatusStrip',family:'socialFamilyList'}}
function rootId(root,suffix){return `${root.id||'social'}-${suffix}`}
function clickByText(selector,words){const list=[...document.querySelectorAll(selector)],want=words.map(x=>x.toLowerCase());const b=list.find(el=>want.some(w=>(el.textContent||'').toLowerCase().includes(w)));b?.click();return !!b}
function goChat(root){if(external(root)){document.getElementById('fsClose')?.click();setTimeout(()=>document.getElementById('friendChatsTab')?.click(),40);return}if(!clickByText('.nav-btn',['chat'])){qs(document,'.nav-btn[data-tab="chat"]')?.click()}}
function openProfile(root){const id=ids(root).edit;const b=document.getElementById(id);if(b){b.click();return}if(external(root)){document.getElementById('friendProfileBtn')?.click();return}window.__ISA_OPEN_PROFILE_STATUS__?.()}
async function openSettings(root){if(external(root)){document.getElementById('friendSettingsBtn')?.click();return}if(typeof window.__ISA_OPEN_GENERAL_SETTINGS__==='function'){window.__ISA_OPEN_GENERAL_SETTINGS__();return}try{await import('./general-settings.js?v=12-unified-settings');window.__ISA_OPEN_GENERAL_SETTINGS__?.()}catch{toast(root,'Configurações não abriram agora.')}}
function openGames(root){if(external(root)){document.getElementById('friendGamesMenuBtn')?.click();return}if(!clickByText('.nav-btn',['joguinhos','jogos']))toast(root,'Joguinhos estão no menu principal do Isa Chat.');}
function focusComposer(root,prefix=''){const ta=document.getElementById(ids(root).caption);if(!ta)return;ta.scrollIntoView({behavior:'smooth',block:'center'});if(prefix&&!ta.value)ta.value=prefix;ta.focus()}
function mediaInput(root,accept){const inp=document.getElementById(ids(root).media);if(!inp)return toast(root,'Envio de mídia ainda não carregou.');inp.accept=accept;inp.click()}
function markFamily(root){const ta=document.getElementById(ids(root).caption);if(!ta)return;const family=qs(root,'.social-family-list');const names=qsa(family,'.social-family-item strong').map(x=>x.textContent.trim()).filter(Boolean);if(!names.length){ta.value+=(ta.value?' ':'')+'@';ta.focus();return}const menu=document.createElement('div');menu.className='isa-create-sheet show';menu.style.position='fixed';menu.style.left='50%';menu.style.top='50%';menu.style.bottom='auto';menu.style.transform='translate(-50%,-50%)';menu.style.zIndex='120090';menu.innerHTML=names.slice(0,12).map(n=>`<button type="button" data-name="${n.replace(/"/g,'&quot;')}"><b>@</b>${n}</button>`).join('');document.body.appendChild(menu);const close=()=>menu.remove();menu.addEventListener('click',e=>{const b=e.target.closest('button[data-name]');if(!b)return;ta.value+=(ta.value?' ':'')+'@'+b.dataset.name+' ';close();ta.focus()});setTimeout(()=>document.addEventListener('pointerdown',e=>{if(!menu.contains(e.target))close()},{once:true,capture:true}),0)}
function openSticker(root){if(typeof window.__ISA_OPEN_STICKER_CREATOR__==='function'){window.__ISA_OPEN_STICKER_CREATOR__();return}const b=document.getElementById('pssStickerBtn')||document.querySelector('[data-pss-sticker],[title*="sticker" i]');if(b){b.click();return}toast(root,'O criador de stickers está carregando…')}
function action(root,type){if(type==='text')focusComposer(root);else if(type==='photo')mediaInput(root,'image/jpeg,image/png,image/webp,image/gif');else if(type==='video')mediaInput(root,'video/mp4,video/webm,video/quicktime');else if(type==='carousel')mediaInput(root,'image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime');else if(type==='audio')toast(root,'🎙️ O card de áudio está pronto no layout; a publicação por áudio será conectada ao gravador do Isa Chat.');else if(type==='mark')markFamily(root);else if(type==='sticker')openSticker(root)}
function header(root,shell){const id=rootId(root,'header');if(document.getElementById(id))return;const h=document.createElement('header');h.id=id;h.className='isa-social-header';h.innerHTML=`<div class="isa-social-logo"><span class="isa-social-logo-heart">💗</span><b>Isa Chat</b><small>Nossa Rede 💕</small></div><input class="isa-social-search" type="search" placeholder="Buscar publicações, pessoas, fotos…" aria-label="Buscar na Nossa Rede"><div class="isa-social-head-actions"><button class="isa-icon-btn" type="button" data-nr4="bell" aria-label="Notificações">🔔</button><button class="isa-icon-btn" type="button" data-nr4="settings" aria-label="Configurações">⚙️</button></div>`;shell.prepend(h);qs(h,'[data-nr4="settings"]').onclick=()=>openSettings(root);qs(h,'[data-nr4="bell"]').onclick=()=>toast(root,'🔔 Notificações do Isa Chat');const search=qs(h,'.isa-social-search');search.addEventListener('input',()=>{const term=search.value.trim().toLocaleLowerCase('pt-BR');qsa(root,'.social-post').forEach(p=>p.classList.toggle('isa-search-hidden',!!term&&!p.textContent.toLocaleLowerCase('pt-BR').includes(term)));qsa(root,'.social-family-item').forEach(p=>p.classList.toggle('isa-search-hidden',!!term&&!p.textContent.toLocaleLowerCase('pt-BR').includes(term)))})}
function sideNav(root){const side=qs(root,'.social-side');if(!side||qs(side,'.isa-social-side-nav'))return;const nav=document.createElement('nav');nav.className='isa-social-side-nav';nav.innerHTML=`<button class="isa-side-link active" type="button"><span class="ico">👥</span>Nossa Rede</button><button class="isa-side-link" type="button" data-go="chat"><span class="ico">💬</span>Chat</button><button class="isa-side-link" type="button" data-go="profile"><span class="ico">👤</span>Perfil</button><button class="isa-side-link" type="button" data-go="settings"><span class="ico">⚙️</span>Configurações</button><button class="isa-side-link" type="button" data-go="games"><span class="ico">🎮</span>Joguinhos</button>`;side.appendChild(nav);qs(nav,'[data-go="chat"]').onclick=()=>goChat(root);qs(nav,'[data-go="profile"]').onclick=()=>openProfile(root);qs(nav,'[data-go="settings"]').onclick=()=>openSettings(root);qs(nav,'[data-go="games"]').onclick=()=>openGames(root)}
function cloud(root){const side=qs(root,'.social-side'),now=qs(side,'.social-now');if(!now||qs(now,'.isa-status-expiry'))return;const span=document.createElement('span');span.className='isa-status-expiry';span.textContent='status temporário • expira conforme definido';now.appendChild(span)}
function rightColumn(root){const right=qs(root,'.social-right');if(!right||right.dataset.nr4==='1')return;right.dataset.nr4='1';const oldH=qs(right,'h3');if(oldH)oldH.style.display='none';const birthday=document.createElement('section');birthday.className='isa-birthday-card';birthday.innerHTML=`<div class="isa-birthday-title">🎂 Aniversários da família</div><div class="isa-birthday-copy">Quando houver aniversariante hoje, o Isa Chat destaca aqui para a família publicar uma homenagem. 💕</div><button class="isa-birthday-btn" type="button">🎁 Criar parabéns</button>`;birthday.querySelector('button').onclick=()=>focusComposer(root,'Feliz aniversário! 🎂💕 ');
const statusWrap=document.createElement('section');statusWrap.className='isa-status-card-wrap';statusWrap.innerHTML='<div class="isa-right-title">💗 Como estou hoje <small>família</small></div>';const strip=document.getElementById(ids(root).status);if(strip)statusWrap.appendChild(strip);
const familyMessage=document.createElement('section');familyMessage.className='isa-family-message';familyMessage.innerHTML='Nossa família,<br>nossas histórias<br>para sempre 💕';
const custom=document.createElement('section');custom.className='isa-custom-card';custom.innerHTML=`<div class="isa-right-title">🎨 Personalize sua experiência</div><div class="isa-custom-grid"><button class="isa-custom-option" data-c="fundos">🖼️ Fundos</button><button class="isa-custom-option" data-c="cores">🎨 Cores</button><button class="isa-custom-option" data-c="fonts">Aa Tipografias</button><button class="isa-custom-option" data-c="status">🕐 Tempo do status</button></div>`;qsa(custom,'button').forEach(b=>b.onclick=()=>b.dataset.c==='status'?openProfile(root):openSettings(root));right.prepend(custom);right.prepend(familyMessage);right.prepend(statusWrap);right.prepend(birthday)}
function composer(root){const comp=qs(root,'.social-composer');if(!comp||qs(comp,'.isa-compose-tools'))return;const ta=document.getElementById(ids(root).caption);if(!ta)return;const tools=document.createElement('div');tools.className='isa-compose-tools';const items=[['text','T','Texto'],['photo','🖼️','Foto'],['video','🎥','Vídeo'],['audio','🎙️','Áudio'],['carousel','▣','Carrossel'],['mark','@','Marcar @'],['sticker','😊','Sticker']];tools.innerHTML=items.map(([a,i,l])=>`<button class="isa-compose-chip" type="button" data-compose="${a}">${i} ${l}</button>`).join('');ta.insertAdjacentElement('afterend',tools);qsa(tools,'[data-compose]').forEach(b=>b.onclick=()=>action(root,b.dataset.compose))}
function mobileTop(root){if(window.matchMedia('(min-width:761px)').matches)return;const shell=qs(root,'.social-shell');if(!shell||qs(root,'.isa-mobile-top-cards'))return;const right=qs(root,'.social-right');if(!right)return;const birthday=qs(right,'.isa-birthday-card'),custom=qs(right,'.isa-custom-card');if(!birthday&&!custom)return;const wrap=document.createElement('div');wrap.className='isa-mobile-top-cards';if(birthday)wrap.appendChild(birthday.cloneNode(true));if(custom)wrap.appendChild(custom.cloneNode(true));const main=qs(root,'.social-main');main?.prepend(wrap);const b=qs(wrap,'.isa-birthday-btn');if(b)b.onclick=()=>focusComposer(root,'Feliz aniversário! 🎂💕 ');qsa(wrap,'.isa-custom-option').forEach(btn=>btn.onclick=()=>btn.dataset.c==='status'?openProfile(root):openSettings(root))}
function bottom(root){if(qs(root,'.isa-mobile-bottom'))return;const bar=document.createElement('nav');bar.className='isa-mobile-bottom';bar.innerHTML=`<button type="button" data-m="home"><span>⌂</span>Início</button><button type="button" data-m="social" class="active"><span>👥</span>Nossa Rede</button><button type="button" data-m="plus" class="isa-mobile-plus">＋</button><button type="button" data-m="chat"><span>💬</span>Chat</button><button type="button" data-m="profile"><span>👤</span>Perfil</button>`;root.appendChild(bar);qs(bar,'[data-m="home"]').onclick=()=>goChat(root);qs(bar,'[data-m="chat"]').onclick=()=>goChat(root);qs(bar,'[data-m="profile"]').onclick=()=>openProfile(root);const plus=qs(bar,'[data-m="plus"]');plus.onclick=()=>toggleSheet(root,plus)}
function toggleSheet(root,anchor){let sheet=document.getElementById(rootId(root,'sheet'));if(!sheet){sheet=document.createElement('div');sheet.id=rootId(root,'sheet');sheet.className='isa-create-sheet';const items=[['photo','🖼️','Foto'],['video','🎥','Vídeo'],['audio','🎙️','Áudio'],['carousel','▣','Carrossel'],['sticker','😊','Sticker'],['mark','@','Marcar @']];sheet.innerHTML=items.map(([a,i,l])=>`<button type="button" data-sheet="${a}"><b>${i}</b>${l}${a==='sticker'?'<small style="display:block;font-size:7px;color:#9b8ba4">remover fundo</small>':''}</button>`).join('');document.body.appendChild(sheet);qsa(sheet,'[data-sheet]').forEach(b=>b.onclick=()=>{sheet.classList.remove('show');action(root,b.dataset.sheet)})}sheet.classList.toggle('show')}
function enhance(root){if(!root||root.dataset.nr4==='1')return;const shell=qs(root,'.social-shell');if(!shell)return;root.dataset.nr4='1';header(root,shell);sideNav(root);cloud(root);rightColumn(root);composer(root);bottom(root);mobileTop(root)}
function enhanceAll(){addCss();enhance(document.getElementById('socialPanel'));enhance(document.getElementById('familySocialOverlay'))}
let pending=0;const observer=new MutationObserver(()=>{clearTimeout(pending);pending=setTimeout(enhanceAll,80)});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('resize',()=>{document.querySelectorAll('[data-nr4="1"]').forEach(r=>mobileTop(r))},{passive:true});addCss();enhanceAll();window.__ISA_ENHANCE_NOSSA_REDE__=enhanceAll;
