import { CONFIG } from './config.js'
const $=id=>document.getElementById(id)
const token=new URLSearchParams(location.hash.replace(/^#/, '')).get('acesso')||''
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm=s=>String(s||'').trim().toLocaleLowerCase('pt-BR')
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`
const COLORS=['#f3a9c9','#bda8ed','#a9d6f3','#a8dcc2','#f2cf85','#efb3a7']
const blankState=()=>({version:1,subjects:[],tasks:[],notes:[],flashcards:[],docs:[],preferences:{pomodoroMinutes:25}})
let state=blankState(),loaded=false,loading=false,saveTimer=null,activeView='home',plannerFilter='today',flashIndex=0,flashFlipped=false,activeDocId=null,pomoSeconds=25*60,pomoTimer=null

async function rpc(name,args={}){
  const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${CONFIG.SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(args),cache:'no-store'})
  let data=null;try{data=await r.json()}catch{}
  if(!r.ok)throw new Error(data?.message||data?.hint||data?.details||'Não foi possível acessar os estudos.')
  return data
}
function isPaloma(){return norm($('friendName')?.textContent)==='paloma'}
function toast(text){const el=$('friendToast');if(!el)return;el.textContent=text;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2400)}
function normalizeState(data){const d=(data&&typeof data==='object'&&!Array.isArray(data))?data:{};return{version:1,subjects:Array.isArray(d.subjects)?d.subjects:[],tasks:Array.isArray(d.tasks)?d.tasks:[],notes:Array.isArray(d.notes)?d.notes:[],flashcards:Array.isArray(d.flashcards)?d.flashcards:[],docs:Array.isArray(d.docs)?d.docs:[],preferences:{pomodoroMinutes:Number(d.preferences?.pomodoroMinutes)||25}}}
async function loadData(){if(loaded||loading)return;loading=true;setSync('Carregando…');try{const res=await rpc('paloma_study_load',{p_token:token});state=normalizeState(res?.data);pomoSeconds=state.preferences.pomodoroMinutes*60;loaded=true;setSync('Salvo no Cantinho');renderAll()}catch(e){setSync('Não foi possível carregar');toast(e.message)}finally{loading=false}}
function scheduleSave(){clearTimeout(saveTimer);setSync('Salvando…');saveTimer=setTimeout(saveData,650)}
async function saveData(){if(!loaded)return;try{await rpc('paloma_study_save',{p_token:token,p_data:state});setSync('Salvo no Cantinho ✓')}catch(e){setSync('Falha ao salvar');toast(e.message)}}
function setSync(text){const el=$('palomaStudySync');if(el)el.textContent=text}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDate(s){if(!s)return null;const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function fmtDate(s){const d=parseDate(s);return d?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(d):'Sem data'}
function subject(id){return state.subjects.find(s=>s.id===id)}
function subjectLabel(id){return subject(id)?.name||'Geral'}
function subjectColor(id){return subject(id)?.color||'#c9b7f1'}
function priorityLabel(v){return v==='alta'?'Alta':v==='baixa'?'Baixa':'Média'}
function startOfWeek(d=new Date()){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x}
function sameDay(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function tasksForFilter(){const now=new Date(),start=startOfWeek(now),end=new Date(start);end.setDate(start.getDate()+7);return [...state.tasks].filter(t=>{const d=parseDate(t.date);if(plannerFilter==='all')return true;if(!d)return false;if(plannerFilter==='today')return sameDay(d,now);if(plannerFilter==='week')return d>=start&&d<end;if(plannerFilter==='month')return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();return true}).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')||(a.time||'99:99').localeCompare(b.time||'99:99'))}

function ensureShell(){
  if($('palomaStudyOverlay'))return
  const ov=document.createElement('div');ov.id='palomaStudyOverlay';ov.className='paloma-study-overlay hidden';ov.innerHTML=`<section id="palomaStudyShell" class="paloma-study-shell" role="dialog" aria-modal="true" aria-label="Estudos da Paloma"><aside class="paloma-study-side"><div class="paloma-study-brand"><span class="badge">🩺 Enfermagem</span><h2>Estudos da Paloma</h2><p>Seu espaço particular para organizar faculdade, revisões e trabalhos.</p></div><nav class="paloma-study-nav"><button data-ps-view="home" class="active">🏠 Início</button><button data-ps-view="subjects">📚 Disciplinas</button><button data-ps-view="planner">🗓️ Planner</button><button data-ps-view="notebook">📒 Caderno digital</button><button data-ps-view="flashcards">🧠 Flashcards</button><button data-ps-view="editor">📝 Editor acadêmico</button></nav><div class="paloma-study-side-foot">🌷 Espaço de organização e estudo. Conteúdos clínicos futuros serão apenas educacionais e não substituem protocolos, docentes ou supervisão de estágio.</div></aside><main class="paloma-study-main"><header class="paloma-study-head"><button id="palomaStudyMobileMenu" class="paloma-study-mobile-menu" type="button">☰</button><strong id="palomaStudyTitle">🏠 Início</strong><span id="palomaStudySync" class="paloma-study-sync">Pronto</span><button id="palomaStudyClose" class="paloma-study-close" type="button">✕</button></header><div class="paloma-study-content"><section id="psViewHome" class="ps-view active"></section><section id="psViewSubjects" class="ps-view"></section><section id="psViewPlanner" class="ps-view"></section><section id="psViewNotebook" class="ps-view"></section><section id="psViewFlashcards" class="ps-view"></section><section id="psViewEditor" class="ps-view"></section></div></main></section>`;document.body.appendChild(ov)
  ov.querySelectorAll('[data-ps-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.psView))
  $('palomaStudyClose').onclick=closeStudies
  $('palomaStudyMobileMenu').onclick=()=> $('palomaStudyShell').classList.toggle('side-open')
  ov.addEventListener('click',e=>{if(e.target===ov)closeStudies()})
  window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!ov.classList.contains('hidden'))closeStudies()})
}
function openStudies(){if(!isPaloma())return;ensureShell();$('palomaStudyOverlay').classList.remove('hidden');document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden';loadData();renderAll()}
function closeStudies(){$('palomaStudyOverlay')?.classList.add('hidden');$('palomaStudyShell')?.classList.remove('side-open');document.documentElement.style.overflow='';document.body.style.overflow='';if(pomoTimer){clearInterval(pomoTimer);pomoTimer=null}}
window.__PALOMA_OPEN_STUDIES__=openStudies
function switchView(view){activeView=view;const titles={home:'🏠 Início',subjects:'📚 Disciplinas',planner:'🗓️ Planner',notebook:'📒 Caderno digital',flashcards:'🧠 Flashcards',editor:'📝 Editor acadêmico'};$('palomaStudyTitle').textContent=titles[view]||'Estudos';document.querySelectorAll('.ps-view').forEach(v=>v.classList.remove('active'));$(`psView${view[0].toUpperCase()+view.slice(1)}`)?.classList.add('active');document.querySelectorAll('[data-ps-view]').forEach(b=>b.classList.toggle('active',b.dataset.psView===view));$('palomaStudyShell')?.classList.remove('side-open');renderView(view)}
function renderAll(){if(!$('palomaStudyOverlay'))return;renderHome();renderSubjects();renderPlanner();renderNotebook();renderFlashcards();renderEditor()}
function renderView(v){({home:renderHome,subjects:renderSubjects,planner:renderPlanner,notebook:renderNotebook,flashcards:renderFlashcards,editor:renderEditor}[v]||(()=>{}))()}

function renderHome(){const el=$('psViewHome');if(!el)return;const open=state.tasks.filter(t=>!t.done).length,todayTasks=state.tasks.filter(t=>!t.done&&t.date===today()).slice(0,5);el.innerHTML=`<div class="ps-hero"><div class="ps-welcome"><h1>Oi, Paloma! 💗</h1><p>Seu cantinho de Enfermagem para juntar disciplinas, prazos, anotações, flashcards e trabalhos sem deixar tudo espalhado.</p></div><div class="ps-focus"><h3>⏱️ Foco rápido</h3><div id="psPomoTime" class="ps-focus-time">${formatPomo()}</div><small>Pomodoro de ${state.preferences.pomodoroMinutes} min</small><button id="psPomoBtn" type="button">▶ Começar foco</button></div></div><div class="ps-stats"><div class="ps-stat"><span>📚</span><strong>${state.subjects.length}</strong><small>disciplinas</small></div><div class="ps-stat"><span>🗓️</span><strong>${open}</strong><small>tarefas pendentes</small></div><div class="ps-stat"><span>📒</span><strong>${state.notes.length}</strong><small>anotações</small></div><div class="ps-stat"><span>🧠</span><strong>${state.flashcards.length}</strong><small>flashcards</small></div></div><div class="ps-grid"><article class="ps-card"><h3>Hoje ✨</h3>${todayTasks.length?todayTasks.map(t=>`<p style="margin:7px 0">${esc(t.time||'')} ${esc(t.title)}</p>`).join(''):'<p>Nenhuma tarefa para hoje. 🌷</p>'}<button type="button" data-home-go="planner" style="margin-top:12px">Abrir planner</button></article><article class="ps-card"><h3>📒 Anotar rapidinho</h3><p>Registre aula, resumo, dúvida ou ideia antes que você esqueça.</p><button type="button" data-home-add-note style="margin-top:12px">Nova anotação</button></article><article class="ps-card"><h3>🧠 Revisão</h3><p>Use seus flashcards para revisar conceitos e conteúdos das disciplinas.</p><button type="button" data-home-go="flashcards" style="margin-top:12px">Revisar agora</button></article></div><div class="ps-coming"><article class="ps-card"><h3>🫀 Anatomia</h3><p>Atlas visual e revisão por sistemas — próxima etapa.</p></article><article class="ps-card"><h3>🩺 Casos fictícios</h3><p>Treino de raciocínio acadêmico com situações simuladas — próxima etapa.</p></article><article class="ps-card"><h3>💊 Farmacologia</h3><p>Organização e revisão de conteúdo, sem prescrição ou cálculo clínico real — próxima etapa.</p></article><article class="ps-card"><h3>🏥 Estágio</h3><p>Checklist acadêmico, horários e registros de aprendizagem — próxima etapa.</p></article></div>`
  el.querySelectorAll('[data-home-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.homeGo));el.querySelector('[data-home-add-note]')?.addEventListener('click',()=>{switchView('notebook');openNoteModal()});$('psPomoBtn')?.addEventListener('click',togglePomo)
}
function formatPomo(){const m=Math.floor(pomoSeconds/60),s=pomoSeconds%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function togglePomo(){const btn=$('psPomoBtn');if(pomoTimer){clearInterval(pomoTimer);pomoTimer=null;if(btn)btn.textContent='▶ Continuar foco';return}if(pomoSeconds<=0)pomoSeconds=state.preferences.pomodoroMinutes*60;pomoTimer=setInterval(()=>{pomoSeconds--;const t=$('psPomoTime');if(t)t.textContent=formatPomo();if(pomoSeconds<=0){clearInterval(pomoTimer);pomoTimer=null;toast('Pomodoro concluído ✨');if(btn)btn.textContent='↻ Começar novamente'}},1000);if(btn)btn.textContent='⏸ Pausar'}

function renderSubjects(){const el=$('psViewSubjects');if(!el)return;el.innerHTML=`<div class="ps-section-title"><div><h2>Disciplinas</h2><p>Organize as matérias do semestre e use-as no planner, caderno e flashcards.</p></div><button class="ps-primary" id="psAddSubject">＋ Disciplina</button></div><div class="ps-list">${state.subjects.length?state.subjects.map(s=>`<article class="ps-item"><span class="ps-color-dot" style="background:${esc(s.color)}"></span><div class="ps-item-main"><strong>${esc(s.name)}</strong><small>${esc(s.semester||'Semestre não informado')}${s.professor?` • ${esc(s.professor)}`:''}</small></div><div class="ps-actions"><button data-edit-subject="${s.id}">Editar</button><button data-del-subject="${s.id}">Excluir</button></div></article>`).join(''):'<div class="ps-empty">Nenhuma disciplina cadastrada ainda. 📚</div>'}</div>`;$('psAddSubject').onclick=()=>openSubjectModal();el.querySelectorAll('[data-edit-subject]').forEach(b=>b.onclick=()=>openSubjectModal(b.dataset.editSubject));el.querySelectorAll('[data-del-subject]').forEach(b=>b.onclick=()=>deleteSubject(b.dataset.delSubject))}
function openSubjectModal(id=''){const current=state.subjects.find(s=>s.id===id);openModal(current?'Editar disciplina':'Nova disciplina',`<form id="psSubjectForm"><div class="ps-form-grid"><div class="ps-field full"><label>Nome da disciplina</label><input name="name" required maxlength="80" value="${esc(current?.name||'')}"></div><div class="ps-field"><label>Semestre/período</label><input name="semester" maxlength="40" placeholder="Ex.: 4º semestre" value="${esc(current?.semester||'')}"></div><div class="ps-field"><label>Professor(a)</label><input name="professor" maxlength="80" value="${esc(current?.professor||'')}"></div><div class="ps-field full"><label>Cor</label><select name="color">${COLORS.map(c=>`<option value="${c}" ${current?.color===c?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="ps-form-actions"><button class="ps-primary" type="submit">Salvar</button></div></form>`,()=>{const f=$('psSubjectForm');f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),obj={id:current?.id||uid(),name:String(fd.get('name')||'').trim(),semester:String(fd.get('semester')||'').trim(),professor:String(fd.get('professor')||'').trim(),color:String(fd.get('color')||COLORS[0])};if(!obj.name)return;if(current)Object.assign(current,obj);else state.subjects.push(obj);scheduleSave();closeModal();renderAll()}})}
function deleteSubject(id){if(!confirm('Excluir esta disciplina? As tarefas e anotações continuam salvas, mas ficam em Geral.'))return;state.subjects=state.subjects.filter(s=>s.id!==id);state.tasks.forEach(t=>{if(t.subjectId===id)t.subjectId=''});state.notes.forEach(n=>{if(n.subjectId===id)n.subjectId=''});state.flashcards.forEach(f=>{if(f.subjectId===id)f.subjectId=''});scheduleSave();renderAll()}
function subjectOptions(selected=''){return `<option value="">Geral</option>${state.subjects.map(s=>`<option value="${s.id}" ${selected===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}`}

function renderPlanner(){const el=$('psViewPlanner');if(!el)return;const list=tasksForFilter();el.innerHTML=`<div class="ps-section-title"><div><h2>Planner acadêmico</h2><p>Organize provas, trabalhos, leituras, aulas e compromissos.</p></div><button class="ps-primary" id="psAddTask">＋ Compromisso</button></div><div class="ps-planner-toolbar"><button data-filter="today" class="${plannerFilter==='today'?'active':''}">Hoje</button><button data-filter="week" class="${plannerFilter==='week'?'active':''}">Semana</button><button data-filter="month" class="${plannerFilter==='month'?'active':''}">Mês</button><button data-filter="all" class="${plannerFilter==='all'?'active':''}">Tudo</button></div><div class="ps-list">${list.length?list.map(t=>`<article class="ps-item ps-task ${t.done?'done':''}"><span class="ps-color-dot" style="background:${subjectColor(t.subjectId)}"></span><div class="ps-item-main"><strong>${esc(t.title)}</strong><small>${fmtDate(t.date)}${t.time?` • ${esc(t.time)}`:''} • ${esc(subjectLabel(t.subjectId))}</small><div class="ps-tags"><span class="ps-tag ps-priority-${esc(t.priority||'media')}">${priorityLabel(t.priority)}</span>${t.type?`<span class="ps-tag">${esc(t.type)}</span>`:''}</div></div><div class="ps-actions"><button data-done-task="${t.id}">${t.done?'↩ Reabrir':'✓ Concluir'}</button><button data-edit-task="${t.id}">Editar</button><button data-del-task="${t.id}">Excluir</button></div></article>`).join(''):'<div class="ps-empty">Nada por aqui nesse período. ✨</div>'}</div>`;$('psAddTask').onclick=()=>openTaskModal();el.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{plannerFilter=b.dataset.filter;renderPlanner()});el.querySelectorAll('[data-done-task]').forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===b.dataset.doneTask);if(t){t.done=!t.done;scheduleSave();renderAll()}});el.querySelectorAll('[data-edit-task]').forEach(b=>b.onclick=()=>openTaskModal(b.dataset.editTask));el.querySelectorAll('[data-del-task]').forEach(b=>b.onclick=()=>{if(confirm('Excluir este compromisso?')){state.tasks=state.tasks.filter(x=>x.id!==b.dataset.delTask);scheduleSave();renderAll()}})}
function openTaskModal(id=''){const current=state.tasks.find(t=>t.id===id);openModal(current?'Editar compromisso':'Novo compromisso',`<form id="psTaskForm"><div class="ps-form-grid"><div class="ps-field full"><label>Título</label><input name="title" required maxlength="120" value="${esc(current?.title||'')}"></div><div class="ps-field"><label>Data</label><input name="date" type="date" value="${esc(current?.date||today())}"></div><div class="ps-field"><label>Horário</label><input name="time" type="time" value="${esc(current?.time||'')}"></div><div class="ps-field"><label>Disciplina</label><select name="subjectId">${subjectOptions(current?.subjectId||'')}</select></div><div class="ps-field"><label>Tipo</label><select name="type"><option>Estudo</option><option>Prova</option><option>Trabalho</option><option>Aula</option><option>Leitura</option><option>Estágio</option><option>Outro</option></select></div><div class="ps-field"><label>Prioridade</label><select name="priority"><option value="baixa" ${current?.priority==='baixa'?'selected':''}>Baixa</option><option value="media" ${!current||current?.priority==='media'?'selected':''}>Média</option><option value="alta" ${current?.priority==='alta'?'selected':''}>Alta</option></select></div><div class="ps-field full"><label>Observações</label><textarea name="notes" maxlength="1000">${esc(current?.notes||'')}</textarea></div></div><div class="ps-form-actions"><button class="ps-primary" type="submit">Salvar</button></div></form>`,()=>{const f=$('psTaskForm');if(current)f.elements.type.value=current.type||'Estudo';f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),obj={id:current?.id||uid(),title:String(fd.get('title')||'').trim(),date:String(fd.get('date')||''),time:String(fd.get('time')||''),subjectId:String(fd.get('subjectId')||''),type:String(fd.get('type')||'Estudo'),priority:String(fd.get('priority')||'media'),notes:String(fd.get('notes')||'').trim(),done:current?.done||false};if(!obj.title)return;if(current)Object.assign(current,obj);else state.tasks.push(obj);scheduleSave();closeModal();renderAll()}})}

function renderNotebook(){const el=$('psViewNotebook');if(!el)return;const notes=[...state.notes].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));el.innerHTML=`<div class="ps-section-title"><div><h2>Caderno digital</h2><p>Resumos, ideias, conteúdos de aula e dúvidas organizados por disciplina.</p></div><button class="ps-primary" id="psAddNote">＋ Anotação</button></div><div class="ps-grid">${notes.length?notes.map(n=>`<article class="ps-card"><span class="ps-tag" style="background:${subjectColor(n.subjectId)}33">${esc(subjectLabel(n.subjectId))}</span><h3 style="margin-top:10px">${esc(n.title)}</h3><div class="ps-note-body">${esc(n.body)}</div>${n.tags?.length?`<div class="ps-tags">${n.tags.map(t=>`<span class="ps-tag">#${esc(t)}</span>`).join('')}</div>`:''}<div class="ps-actions" style="margin-top:12px"><button data-edit-note="${n.id}">Editar</button><button data-del-note="${n.id}">Excluir</button></div></article>`).join(''):'<div class="ps-empty" style="grid-column:1/-1">Seu caderno está vazio. Comece com uma anotação de aula. 📒</div>'}</div>`;$('psAddNote').onclick=()=>openNoteModal();el.querySelectorAll('[data-edit-note]').forEach(b=>b.onclick=()=>openNoteModal(b.dataset.editNote));el.querySelectorAll('[data-del-note]').forEach(b=>b.onclick=()=>{if(confirm('Excluir esta anotação?')){state.notes=state.notes.filter(n=>n.id!==b.dataset.delNote);scheduleSave();renderAll()}})}
function openNoteModal(id=''){const current=state.notes.find(n=>n.id===id);openModal(current?'Editar anotação':'Nova anotação',`<form id="psNoteForm"><div class="ps-form-grid"><div class="ps-field full"><label>Título</label><input name="title" required maxlength="120" value="${esc(current?.title||'')}"></div><div class="ps-field"><label>Disciplina</label><select name="subjectId">${subjectOptions(current?.subjectId||'')}</select></div><div class="ps-field"><label>Tags</label><input name="tags" maxlength="120" placeholder="Ex.: revisão, prova, aula 4" value="${esc((current?.tags||[]).join(', '))}"></div><div class="ps-field full"><label>Anotação</label><textarea name="body" required maxlength="12000" style="min-height:240px">${esc(current?.body||'')}</textarea></div></div><div class="ps-form-actions"><button class="ps-primary" type="submit">Salvar</button></div></form>`,()=>{const f=$('psNoteForm');f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),obj={id:current?.id||uid(),title:String(fd.get('title')||'').trim(),subjectId:String(fd.get('subjectId')||''),tags:String(fd.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,8),body:String(fd.get('body')||'').trim(),updatedAt:Date.now()};if(!obj.title||!obj.body)return;if(current)Object.assign(current,obj);else state.notes.push(obj);scheduleSave();closeModal();renderAll()}})}

function renderFlashcards(){const el=$('psViewFlashcards');if(!el)return;const cards=state.flashcards;if(flashIndex>=cards.length)flashIndex=0;const c=cards[flashIndex];el.innerHTML=`<div class="ps-section-title"><div><h2>Flashcards</h2><p>Crie perguntas e respostas para revisar de forma rápida.</p></div><button class="ps-primary" id="psAddFlash">＋ Flashcard</button></div>${cards.length?`<div class="ps-flash-stage"><div><div id="psFlashCard" class="ps-flash-card"><div><div class="face">${esc(flashFlipped?c.answer:c.question)}</div><small>${flashFlipped?'Resposta':'Pergunta'} • toque para virar</small></div></div><div class="ps-actions" style="justify-content:center;margin-top:12px"><button id="psFlashPrev">← Anterior</button><button id="psFlashFlip">Virar</button><button id="psFlashNext">Próximo →</button></div></div><div class="ps-card"><span class="ps-tag" style="background:${subjectColor(c.subjectId)}33">${esc(subjectLabel(c.subjectId))}</span><h3 style="margin-top:12px">Revisão ${flashIndex+1}/${cards.length}</h3><p>${esc(c.note||'Use este cartão para revisar o conteúdo.')}</p><div class="ps-actions" style="margin-top:12px"><button data-edit-flash="${c.id}">Editar</button><button data-del-flash="${c.id}">Excluir</button></div></div></div>`:'<div class="ps-empty">Nenhum flashcard ainda. Crie o primeiro para começar sua revisão. 🧠</div>'}`;$('psAddFlash').onclick=()=>openFlashModal();if(c){const flip=()=>{flashFlipped=!flashFlipped;renderFlashcards()};$('psFlashCard').onclick=flip;$('psFlashFlip').onclick=flip;$('psFlashPrev').onclick=()=>{flashIndex=(flashIndex-1+cards.length)%cards.length;flashFlipped=false;renderFlashcards()};$('psFlashNext').onclick=()=>{flashIndex=(flashIndex+1)%cards.length;flashFlipped=false;renderFlashcards()};el.querySelector('[data-edit-flash]')?.addEventListener('click',()=>openFlashModal(c.id));el.querySelector('[data-del-flash]')?.addEventListener('click',()=>{if(confirm('Excluir este flashcard?')){state.flashcards=state.flashcards.filter(f=>f.id!==c.id);flashIndex=0;flashFlipped=false;scheduleSave();renderAll()}})}}
function openFlashModal(id=''){const current=state.flashcards.find(f=>f.id===id);openModal(current?'Editar flashcard':'Novo flashcard',`<form id="psFlashForm"><div class="ps-form-grid"><div class="ps-field full"><label>Pergunta / frente</label><textarea name="question" required maxlength="1500">${esc(current?.question||'')}</textarea></div><div class="ps-field full"><label>Resposta / verso</label><textarea name="answer" required maxlength="2500">${esc(current?.answer||'')}</textarea></div><div class="ps-field"><label>Disciplina</label><select name="subjectId">${subjectOptions(current?.subjectId||'')}</select></div><div class="ps-field"><label>Observação</label><input name="note" maxlength="180" value="${esc(current?.note||'')}"></div></div><div class="ps-form-actions"><button class="ps-primary" type="submit">Salvar</button></div></form>`,()=>{const f=$('psFlashForm');f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),obj={id:current?.id||uid(),question:String(fd.get('question')||'').trim(),answer:String(fd.get('answer')||'').trim(),subjectId:String(fd.get('subjectId')||''),note:String(fd.get('note')||'').trim()};if(!obj.question||!obj.answer)return;if(current)Object.assign(current,obj);else state.flashcards.push(obj);flashIndex=0;flashFlipped=false;scheduleSave();closeModal();renderAll()}})}

function renderEditor(){const el=$('psViewEditor');if(!el)return;if(activeDocId&&!state.docs.some(d=>d.id===activeDocId))activeDocId=null;const doc=state.docs.find(d=>d.id===activeDocId);el.innerHTML=`<div class="ps-section-title"><div><h2>Editor acadêmico</h2><p>Rascunhos de trabalhos, relatórios e textos acadêmicos com formatação básica.</p></div><button class="ps-primary" id="psNewDoc">＋ Documento</button></div>${doc?`<div class="ps-field"><label>Título do documento</label><input id="psDocTitle" maxlength="140" value="${esc(doc.title)}"></div><div class="ps-editor-toolbar"><button data-cmd="bold"><b>B</b></button><button data-cmd="italic"><i>I</i></button><button data-cmd="underline"><u>U</u></button><button data-cmd="formatBlock" data-val="h2">Título</button><button data-cmd="insertUnorderedList">• Lista</button><button data-cmd="insertOrderedList">1. Lista</button><button data-cmd="justifyLeft">≡</button><button data-cmd="justifyCenter">≣</button></div><div id="psEditorArea" class="ps-editor" contenteditable="true">${doc.html||''}</div><div class="ps-form-actions"><button class="ps-soft-btn" id="psPrintDoc">🖨️ Imprimir / PDF</button><button class="ps-primary" id="psSaveDoc">Salvar documento</button></div><div class="ps-save-note">Dica: no celular/computador, “Imprimir / PDF” abre a impressão do navegador, onde normalmente é possível escolher “Salvar como PDF”.</div>`:'<div class="ps-empty">Escolha um documento abaixo ou crie um novo. 📝</div>'}<div class="ps-editor-docs">${state.docs.map(d=>`<article class="ps-item"><div class="ps-item-main"><strong>${esc(d.title||'Sem título')}</strong><small>Atualizado ${new Date(d.updatedAt||Date.now()).toLocaleDateString('pt-BR')}</small></div><div class="ps-actions"><button data-open-doc="${d.id}">Abrir</button><button data-del-doc="${d.id}">Excluir</button></div></article>`).join('')}</div>`;$('psNewDoc').onclick=()=>{const d={id:uid(),title:'Novo documento',html:'<p>Comece a escrever aqui…</p>',updatedAt:Date.now()};state.docs.unshift(d);activeDocId=d.id;scheduleSave();renderEditor()};el.querySelectorAll('[data-open-doc]').forEach(b=>b.onclick=()=>{activeDocId=b.dataset.openDoc;renderEditor()});el.querySelectorAll('[data-del-doc]').forEach(b=>b.onclick=()=>{if(confirm('Excluir este documento?')){state.docs=state.docs.filter(d=>d.id!==b.dataset.delDoc);if(activeDocId===b.dataset.delDoc)activeDocId=null;scheduleSave();renderEditor()}});if(doc){el.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,b.dataset.val||null);$('psEditorArea')?.focus()});$('psSaveDoc').onclick=()=>{doc.title=$('psDocTitle').value.trim()||'Sem título';doc.html=$('psEditorArea').innerHTML;doc.updatedAt=Date.now();scheduleSave();renderEditor();toast('Documento salvo ✨')};$('psPrintDoc').onclick=()=>printDocument(doc,$('psDocTitle').value,$('psEditorArea').innerHTML)}}
function printDocument(doc,title,html){const w=window.open('','_blank','noopener,noreferrer');if(!w)return toast('O navegador bloqueou a janela de impressão.');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title||doc.title)}</title><style>body{font:16px/1.6 Arial,sans-serif;max-width:800px;margin:40px auto;padding:0 24px;color:#222}h1,h2,h3{line-height:1.25}@media print{body{margin:0 auto}}</style></head><body><h1>${esc(title||doc.title)}</h1>${html}</body></html>`);w.document.close();setTimeout(()=>w.print(),300)}

function openModal(title,body,onReady){closeModal();const m=document.createElement('div');m.id='psModal';m.className='ps-modal';m.innerHTML=`<div class="ps-modal-card"><div class="ps-modal-head"><h3>${esc(title)}</h3><button id="psModalClose" class="ps-modal-close" type="button">✕</button></div>${body}</div>`;document.body.appendChild(m);$('psModalClose').onclick=closeModal;m.addEventListener('click',e=>{if(e.target===m)closeModal()});onReady?.()}
function closeModal(){$('psModal')?.remove()}

function ensureEntryPoints(){if(!isPaloma())return;ensureShell();const side=document.querySelector('.friend-sidebar');if(side&&!$('palomaStudyEntry')){const b=document.createElement('button');b.id='palomaStudyEntry';b.className='paloma-study-entry';b.type='button';b.innerHTML='📚 Estudos da Paloma <small>Planner, caderno, flashcards e trabalhos</small>';b.onclick=openStudies;const profile=document.querySelector('.friend-profile');profile?.after(b)}
  const head=document.querySelector('.friend-thread-head');if(head&&!$('palomaStudyHeaderBtn')){const b=document.createElement('button');b.id='palomaStudyHeaderBtn';b.className='back-btn';b.type='button';b.title='Estudos da Paloma';b.textContent='📚';b.onclick=openStudies;head.appendChild(b)}
  const pop=$('palomaGamesPop');if(pop&&!pop.querySelector('[data-open-studies]')){const b=document.createElement('button');b.type='button';b.dataset.openStudies='1';b.textContent='📚 Estudos';b.onclick=()=>{pop.classList.add('hidden');openStudies()};pop.prepend(b)}
}
function wire(){if(isPaloma())ensureEntryPoints()}
const obs=new MutationObserver(wire);obs.observe(document.body,{childList:true,subtree:true,characterData:true});let tries=0;const timer=setInterval(()=>{wire();if(++tries>160)clearInterval(timer)},400);wire()
