import { CONFIG } from './config.js'
const $=id=>document.getElementById(id)
const mascots=['🐼','🐰','🦊','🐱','🐶','🐻','🐨','🦄','🐸','🐯','🦋','🌷','⭐','💜']
function token(){try{const ref=new URL(CONFIG.SUPABASE_URL).hostname.split('.')[0],raw=localStorage.getItem(`sb-${ref}-auth-token`);if(!raw)return null;const d=JSON.parse(raw);return d?.access_token||d?.currentSession?.access_token||d?.session?.access_token||null}catch{return null}}
function jwtSub(t){try{const p=t.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(decodeURIComponent(escape(atob(p.padEnd(Math.ceil(p.length/4)*4,'='))))).sub}catch{return null}}
async function currentProfile(){const t=token(),sub=t&&jwtSub(t);if(!t||!sub)return null;const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/family_members?auth_user_id=eq.${encodeURIComponent(sub)}&active=eq.true&select=id,avatar_ref&limit=1`,{headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${t}`},cache:'no-store'});const d=await r.json().catch(()=>[]);return Array.isArray(d)?d[0]||null:null}
async function setMascot(emoji){const t=token();if(!t)throw new Error('Sem sessão');const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/rpc/set_my_mascot`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({p_emoji:emoji})});if(!r.ok)throw new Error('Não foi possível salvar o mascote.');applyMascot(emoji)}
function applyMascot(emoji){const a=$('myAvatar');if(!a)return;a.textContent=emoji;const b=$('myAvatarBtn');if(b){b.style.backgroundImage='none';b.classList.add('mascot-avatar')}}
async function refresh(){const p=await currentProfile().catch(()=>null);if(p?.avatar_ref?.startsWith('emoji:'))applyMascot(p.avatar_ref.slice(6))}
function openChooser(){const dlg=$('simpleDialog'),c=$('dialogContent');if(!dlg||!c)return;c.innerHTML=`<h3>Seu perfil 💜</h3><p class="muted">Escolha uma foto ou um mascote.</p><button id="chooseProfilePhoto" class="soft-btn" type="button">📷 Usar ou trocar foto</button><div class="mascot-grid">${mascots.map(e=>`<button type="button" class="mascot-choice" data-mascot="${e}">${e}</button>`).join('')}</div>`;dlg.showModal();$('chooseProfilePhoto').onclick=()=>{dlg.close();$('profileAvatarInput')?.click()};document.querySelectorAll('[data-mascot]').forEach(b=>b.onclick=async()=>{try{b.disabled=true;await setMascot(b.dataset.mascot);dlg.close()}catch(e){b.disabled=false}})}
function bind(){const b=$('myAvatarBtn');if(!b)return;b.onclick=openChooser;refresh();const input=$('profileAvatarInput');if(input&&!input.dataset.mascotBound){input.dataset.mascotBound='1';input.addEventListener('change',()=>setTimeout(refresh,1800))}}
if(!document.querySelector('style[data-mascot-style]')){const s=document.createElement('style');s.dataset.mascotStyle='1';s.textContent='.mascot-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:8px;margin-top:14px}.mascot-choice{border:0;border-radius:14px;background:#f3ebff;padding:12px;font-size:25px;cursor:pointer}.mascot-choice:hover{transform:translateY(-2px);background:#ffe8f4}.mascot-avatar{font-size:24px}.mascot-avatar #myAvatar{font-size:26px}@media(max-width:520px){.mascot-grid{grid-template-columns:repeat(5,1fr)}}';document.head.appendChild(s)}
const obs=new MutationObserver(bind);obs.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('load',()=>setTimeout(bind,300));bind()
