import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'
import { CONFIG } from './config.js'
const dbM=createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}})
const $m=id=>document.getElementById(id)
let meM=null,mapItem=null,nodes=[],selectedId=null,saveTimer=null,channel=null
function css(){if(document.querySelector('link[href^="study-mindmap.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='study-mindmap.css?v=1';document.head.appendChild(l)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const x=$m('toast');if(!x)return;x.textContent=t;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),1600)}
async function identity(){if(meM)return meM;const {data:{user}}=await dbM.auth.getUser();if(!user)throw new Error('Sem sessão');const {data,error}=await dbM.from('family_members').select('id,family_id,display_name').eq('auth_user_id',user.id).eq('active',true).single();if(error)throw error;meM=data;return data}
function scopeInfo(){const v=$m('studyScope')?.value||'private';return v==='private'?{conversation_id:null,visibility:'private'}:{conversation_id:v,visibility:'group'}}
function lineSvg(){return nodes.filter(n=>n.parent).map(n=>{const p=nodes.find(x=>x.id===n.parent);if(!p)return'';return `<line x1="${p.x+75}" y1="${p.y+28}" x2="${n.x+75}" y2="${n.y+28}" stroke="#b9a6d9" stroke-width="3" stroke-linecap="round" opacity=".65"/>`}).join('')}
function render(){const c=$m('mindCanvas');if(!c)return;c.innerHTML=`<svg class="mind-svg" viewBox="0 0 1600 1000" preserveAspectRatio="none">${lineSvg()}</svg>${nodes.map(n=>`<button type="button" class="mind-node ${n.parent?'':'root'} ${selectedId===n.id?'selected':''}" data-node="${n.id}" data-tone="${n.tone||'lilac'}" style="left:${n.x}px;top:${n.y}px">${esc(n.text)}</button>`).join('')}`;document.querySelectorAll('[data-node]').forEach(bindNode)}
function bindNode(el){el.onclick=()=>{selectedId=el.dataset.node;render()};el.ondblclick=()=>editNode(el.dataset.node);el.onpointerdown=e=>{if(e.button!==0)return;selectedId=el.dataset.node;const n=nodes.find(x=>x.id===selectedId);if(!n)return;el.setPointerCapture?.(e.pointerId);const startX=e.clientX,startY=e.clientY,ox=n.x,oy=n.y;const move=ev=>{n.x=Math.max(10,Math.min(1400,ox+ev.clientX-startX));n.y=Math.max(10,Math.min(900,oy+ev.clientY-startY));render();schedule()};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up)};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)}}
function addBranch(){const parent=nodes.find(x=>x.id===selectedId)||nodes[0];if(!parent)return;const idx=nodes.filter(x=>x.parent===parent.id).length;nodes.push({id:crypto.randomUUID(),text:'Nova ideia',parent:parent.id,x:parent.x+230,y:parent.y+(idx-1)*110,tone:['pink','blue','mint','yellow','lilac'][nodes.length%5]});selectedId=nodes.at(-1).id;render();schedule()}
function editNode(id){const n=nodes.find(x=>x.id===id);if(!n)return;const v=prompt('Texto do tópico:',n.text);if(v===null)return;n.text=v.trim()||n.text;render();schedule()}
function removeNode(){const n=nodes.find(x=>x.id===selectedId);if(!n||!n.parent)return toast('O tópico central não pode ser removido.');const remove=new Set([n.id]);let changed=true;while(changed){changed=false;for(const x of nodes)if(x.parent&&remove.has(x.parent)&&!remove.has(x.id)){remove.add(x.id);changed=true}}nodes=nodes.filter(x=>!remove.has(x.id));selectedId=nodes[0]?.id||null;render();schedule()}
async function load(){await identity();mapItem=null;if(channel){dbM.removeChannel(channel);channel=null}const si=scopeInfo();let q=dbM.from('study_items').select('id,title,content,conversation_id,visibility,updated_at').eq('item_type','mindmap').eq('title','Mapa Mental');q=si.visibility==='private'?q.eq('owner_member_id',meM.id).is('conversation_id',null).eq('visibility','private'):q.eq('conversation_id',si.conversation_id).eq('visibility','group');const {data,error}=await q.order('updated_at',{ascending:false}).limit(1);if(error)return;mapItem=data?.[0]||null;nodes=Array.isArray(mapItem?.content?.nodes)&&mapItem.content.nodes.length?mapItem.content.nodes:[{id:crypto.randomUUID(),text:'Tema central',parent:null,x:650,y:420,tone:'lilac'}];selectedId=nodes[0].id;render();$m('mindStatus').textContent=mapItem?'Salvo ✓':'Novo mapa';if(mapItem){channel=dbM.channel(`mind-${mapItem.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'study_items',filter:`id=eq.${mapItem.id}`},payload=>{if(document.activeElement?.matches?.('[data-node]'))return;nodes=payload.new?.content?.nodes||nodes;render();$m('mindStatus').textContent='Atualizado em tempo real ✓'}).subscribe()}}
function schedule(){$m('mindStatus').textContent='Salvando…';clearTimeout(saveTimer);saveTimer=setTimeout(save,700)}
async function save(){await identity();clearTimeout(saveTimer);const si=scopeInfo();if(!mapItem){const {data,error}=await dbM.from('study_items').insert({family_id:meM.family_id,conversation_id:si.conversation_id,owner_member_id:meM.id,item_type:'mindmap',title:'Mapa Mental',content:{nodes},visibility:si.visibility,allowed_member_ids:[],updated_by:meM.id}).select('id,title,content,conversation_id,visibility,updated_at').single();if(error){console.error(error);$m('mindStatus').textContent='Erro';return}mapItem=data;await load()}else{const {error}=await dbM.from('study_items').update({content:{nodes},updated_by:meM.id}).eq('id',mapItem.id);if(error){console.error(error);$m('mindStatus').textContent='Erro';return}}$m('mindStatus').textContent='Salvo ✓'}
function mount(){css();const grid=document.querySelector('.study-home-grid'),panel=$m('studyPanel');if(!grid||!panel)return false;if(!$m('openMindmapTool')){const b=document.createElement('button');b.id='openMindmapTool';b.type='button';b.className='study-tool-card';b.style.background='linear-gradient(145deg,#e2efff,#eadfff 48%,#dff5e9)';b.innerHTML='<span class="tool-symbol">🧠</span><strong>Mapa Mental</strong><small>Crie tópicos, ramificações e organize ideias visualmente.</small>';grid.appendChild(b)}if(!$m('studyMindmap')){const s=document.createElement('div');s.id='studyMindmap';s.className='study-workspace hidden';s.innerHTML=`<button id="mindBack" class="study-back" type="button">← Mesa de Estudos</button><div class="mind-shell"><section class="mind-panel"><div class="mind-top"><h3>Mapa Mental</h3><span id="mindStatus" class="mind-status">Carregando…</span><button id="mindAdd" type="button">＋ Ramificação</button><button id="mindEdit" type="button">Editar tópico</button><button id="mindRemove" type="button">Excluir tópico</button><button id="mindSave" type="button">Salvar agora</button></div><div class="mind-hint">Clique para selecionar • arraste para mover • clique duas vezes para editar.</div><div id="mindCanvas" class="mind-canvas"></div></section></div>`;panel.appendChild(s)}if(!$m('openMindmapTool').dataset.bound){$m('openMindmapTool').dataset.bound='1';$m('openMindmapTool').onclick=()=>{$m('studyHome').classList.add('hidden');['studyCalculator','studyDocument','studyRandomizer','studyFlashcards','studyIdeas'].forEach(id=>$m(id)?.classList.add('hidden'));$m('studyMindmap').classList.remove('hidden');load()};$m('mindBack').onclick=()=>{$m('studyMindmap').classList.add('hidden');$m('studyHome').classList.remove('hidden')};$m('mindAdd').onclick=addBranch;$m('mindEdit').onclick=()=>selectedId&&editNode(selectedId);$m('mindRemove').onclick=removeNode;$m('mindSave').onclick=()=>save().then(()=>toast('Mapa salvo ✓'));$m('studyScope')?.addEventListener('change',()=>{if(!$m('studyMindmap').classList.contains('hidden'))load()})}return true}
function wait(){if(mount())return;const o=new MutationObserver(()=>{if(mount())o.disconnect()});o.observe(document.documentElement,{childList:true,subtree:true})}
wait();dbM.auth.onAuthStateChange((_e,s)=>{if(!s){meM=null;mapItem=null;nodes=[]}})
