import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'
import { CONFIG } from './config.js'
const dbI=createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}})
const $i=id=>document.getElementById(id)
let meI=null,board=null,notes=[],saveTimer=null,channel=null,drag=null,newTone='yellow'
const TONES=['yellow','pink','lilac','blue','mint','peach']
function css(){if(document.querySelector('link[href^="study-ideas.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='study-ideas.css?v=2';document.head.appendChild(l)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const x=$i('toast');if(!x)return;x.textContent=t;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),1700)}
async function identity(){if(meI)return meI;const {data:{user}}=await dbI.auth.getUser();if(!user)throw new Error('Sem sessão');const {data,error}=await dbI.from('family_members').select('id,family_id,display_name').eq('auth_user_id',user.id).eq('active',true).single();if(error)throw error;meI=data;return data}
function scopeInfo(){const v=$i('studyScope')?.value||'private';return v==='private'?{conversation_id:null,visibility:'private'}:{conversation_id:v,visibility:'group'}}
function canDeleteNote(n){return !n.owner_id||n.owner_id===meI?.id||scopeInfo().visibility==='private'}
function normalize(n,i){return {id:n.id||crypto.randomUUID(),text:n.text||'',tone:TONES.includes(n.tone)?n.tone:'yellow',by:n.by||'',owner_id:n.owner_id||null,x:Number.isFinite(+n.x)?Math.max(0,+n.x):30+(i%4)*220,y:Number.isFinite(+n.y)?Math.max(0,+n.y):35+Math.floor(i/4)*190,rotate:Number.isFinite(+n.rotate)?+n.rotate:([-2,1,-1,2,0][i%5])}}
function boardDimensions(){const c=$i('ideasCanvas');return {w:Math.max(c?.clientWidth||900,320),h:Math.max(c?.clientHeight||620,420)}}
function clampPosition(n){const {w,h}=boardDimensions();n.x=Math.max(6,Math.min(w-190,n.x));n.y=Math.max(8,Math.min(h-150,n.y))}
function render(){const c=$i('ideasCanvas');if(!c)return;notes=notes.map(normalize);c.innerHTML=notes.map((n,idx)=>`<article class="idea-note" data-note-id="${n.id}" data-tone="${n.tone}" style="left:${n.x}px;top:${n.y}px;transform:rotate(${n.rotate}deg)"><div class="idea-pin" data-drag-note="${idx}" title="Arraste pelo pino"></div><div class="idea-note-head"><span class="idea-author">${esc(n.by||'')}</span><button type="button" data-edit-note="${idx}" title="Editar">Editar</button>${canDeleteNote(n)?`<button type="button" data-remove-note="${idx}" title="Excluir">Excluir</button>`:''}</div><div class="idea-text" data-drag-note="${idx}">${esc(n.text||'')}</div></article>`).join('')||'<div class="ideas-empty"><strong>Seu quadro está vazio.</strong><span>Escolha uma cor, escreva uma nota e clique em “Fixar no quadro”.</span></div>'
  document.querySelectorAll('[data-remove-note]').forEach(x=>x.onclick=e=>{e.stopPropagation();const idx=+x.dataset.removeNote;if(!canDeleteNote(notes[idx]))return toast('Você só pode excluir seus próprios post-its.');if(!confirm('Excluir este post-it?'))return;notes.splice(idx,1);render();schedule()})
  document.querySelectorAll('[data-edit-note]').forEach(x=>x.onclick=e=>{e.stopPropagation();editNote(+x.dataset.editNote)})
  document.querySelectorAll('[data-drag-note]').forEach(x=>x.onpointerdown=startDrag)
}
function startDrag(e){if(e.button!==undefined&&e.button!==0)return;const idx=+e.currentTarget.dataset.dragNote,n=notes[idx],card=e.currentTarget.closest('.idea-note'),canvas=$i('ideasCanvas');if(!n||!card||!canvas)return;e.preventDefault();const r=card.getBoundingClientRect(),cr=canvas.getBoundingClientRect();drag={idx,dx:e.clientX-r.left,dy:e.clientY-r.top,cr,card};card.classList.add('dragging');e.currentTarget.setPointerCapture?.(e.pointerId);window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',endDrag,{once:true})}
function moveDrag(e){if(!drag)return;const n=notes[drag.idx];n.x=e.clientX-drag.cr.left-drag.dx+$i('ideasCanvas').scrollLeft;n.y=e.clientY-drag.cr.top-drag.dy+$i('ideasCanvas').scrollTop;clampPosition(n);drag.card.style.left=`${n.x}px`;drag.card.style.top=`${n.y}px`}
function endDrag(){if(!drag)return;drag.card.classList.remove('dragging');drag=null;window.removeEventListener('pointermove',moveDrag);schedule()}
function toneButtons(){return TONES.map(t=>`<button type="button" class="idea-tone ${t===newTone?'active':''}" data-new-tone="${t}" data-tone="${t}" aria-label="Cor ${t}"></button>`).join('')}
function bindComposer(){document.querySelectorAll('[data-new-tone]').forEach(b=>b.onclick=()=>{newTone=b.dataset.newTone;document.querySelectorAll('[data-new-tone]').forEach(x=>x.classList.toggle('active',x.dataset.newTone===newTone))})}
async function addFromComposer(){await identity();const ta=$i('ideaComposerText'),text=ta.value.trim();if(!text)return toast('Digite o que deseja colocar no post-it.');const {w}=boardDimensions(),count=notes.length;const x=Math.max(18,Math.min(w-210,25+(count%4)*215)),y=30+(Math.floor(count/4)%4)*175;notes.push({id:crypto.randomUUID(),text,tone:newTone,by:meI.display_name,owner_id:meI.id,x,y,rotate:[-2,1,-1,2,0][count%5]});ta.value='';render();schedule();toast('Post-it fixado no quadro')}
function editNote(idx){const n=notes[idx];if(!n)return;if(n.owner_id&&n.owner_id!==meI?.id&&scopeInfo().visibility==='group')return toast('No grupo, cada pessoa edita os próprios post-its.');const text=prompt('Editar post-it:',n.text);if(text===null)return;const trimmed=text.trim();if(!trimmed)return toast('O post-it não pode ficar vazio.');n.text=trimmed;render();schedule()}
async function load(){await identity();board=null;notes=[];if(channel){dbI.removeChannel(channel);channel=null}const si=scopeInfo();let q=dbI.from('study_items').select('id,title,content,conversation_id,visibility,updated_at,owner_member_id').eq('item_type','idea_board').eq('title','Quadro de Ideias');q=si.visibility==='private'?q.eq('owner_member_id',meI.id).is('conversation_id',null).eq('visibility','private'):q.eq('conversation_id',si.conversation_id).eq('visibility','group');const {data,error}=await q.order('updated_at',{ascending:false}).limit(1);if(error){console.error(error);return}board=data?.[0]||null;notes=(Array.isArray(board?.content?.notes)?board.content.notes:[]).map(normalize);render();$i('ideasStatus').textContent=board?'Salvo ✓':'Novo quadro';if(board){channel=dbI.channel(`ideas-${board.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'study_items',filter:`id=eq.${board.id}`},payload=>{if(drag)return;notes=(Array.isArray(payload.new?.content?.notes)?payload.new.content.notes:[]).map(normalize);render();$i('ideasStatus').textContent='Atualizado em tempo real ✓'}).subscribe()}}
function schedule(){$i('ideasStatus').textContent='Salvando…';clearTimeout(saveTimer);saveTimer=setTimeout(save,500)}
async function save(){await identity();clearTimeout(saveTimer);const si=scopeInfo();if(!board){const {data,error}=await dbI.from('study_items').insert({family_id:meI.family_id,conversation_id:si.conversation_id,owner_member_id:meI.id,item_type:'idea_board',title:'Quadro de Ideias',content:{notes},visibility:si.visibility,allowed_member_ids:[],updated_by:meI.id}).select('id,title,content,conversation_id,visibility,updated_at,owner_member_id').single();if(error){console.error(error);$i('ideasStatus').textContent='Erro ao salvar';return}board=data;await load()}else{const {error}=await dbI.from('study_items').update({content:{notes},updated_by:meI.id}).eq('id',board.id);if(error){console.error(error);$i('ideasStatus').textContent='Erro ao salvar';return}}$i('ideasStatus').textContent='Salvo ✓'}
async function clearMine(){await identity();const group=scopeInfo().visibility==='group';const mine=notes.filter(n=>!n.owner_id||n.owner_id===meI.id);if(!mine.length)return toast(group?'Você não tem post-its para apagar.':'O quadro já está vazio.');const msg=group?'Apagar todos os post-its que você criou neste grupo?':'Apagar TODOS os post-its deste quadro?';if(!confirm(msg))return;notes=group?notes.filter(n=>n.owner_id&&n.owner_id!==meI.id):[];render();schedule();toast(group?'Seus post-its foram apagados':'Quadro limpo')}
function mount(){css();const grid=document.querySelector('.study-home-grid'),panel=$i('studyPanel');if(!grid||!panel)return false;if(!$i('openIdeasTool')){const b=document.createElement('button');b.id='openIdeasTool';b.type='button';b.className='study-tool-card';b.style.background='linear-gradient(145deg,#fff0bd,#ffddea 48%,#e6dbff)';b.innerHTML='<span class="tool-symbol">▧</span><strong>Quadro de Post-its</strong><small>Estudos, lembretes e ideias em um mural individual ou de grupo.</small>';grid.appendChild(b)}else{$i('openIdeasTool').querySelector('strong').textContent='Quadro de Post-its';const sm=$i('openIdeasTool').querySelector('small');if(sm)sm.textContent='Estudos, lembretes e ideias em um mural individual ou de grupo.'}
if(!$i('studyIdeas')){const s=document.createElement('div');s.id='studyIdeas';s.className='study-workspace hidden';s.innerHTML=`<button id="ideasBack" class="study-back" type="button">← Mesa de Estudos</button><div class="ideas-shell"><section class="ideas-board"><div class="ideas-top"><div><h3>Quadro de Post-its</h3><span id="ideasStatus" class="ideas-status">Carregando…</span></div><button id="ideasSave" type="button">Salvar agora</button><button id="ideasClearMine" type="button" class="ideas-danger">Apagar meus post-its</button></div><div class="ideas-composer"><div class="idea-color-picker"><span>Cor do post-it</span><div id="ideaTonePicker">${toneButtons()}</div></div><textarea id="ideaComposerText" maxlength="800" placeholder="Ex.: Revisar a matéria de Ciências; lembrar de levar cartolina; ideia para a apresentação..."></textarea><button id="ideasPinBtn" type="button">Fixar no quadro</button></div><div id="ideasCanvas" class="ideas-canvas"></div></section></div>`;panel.appendChild(s)}else{const old=$i('ideasCanvas');if(old&&!$i('ideaComposerText')){const top=$i('studyIdeas').querySelector('.ideas-top');if(top){top.innerHTML=`<div><h3>Quadro de Post-its</h3><span id="ideasStatus" class="ideas-status">Carregando…</span></div><button id="ideasSave" type="button">Salvar agora</button><button id="ideasClearMine" type="button" class="ideas-danger">Apagar meus post-its</button>`;const composer=document.createElement('div');composer.className='ideas-composer';composer.innerHTML=`<div class="idea-color-picker"><span>Cor do post-it</span><div id="ideaTonePicker">${toneButtons()}</div></div><textarea id="ideaComposerText" maxlength="800" placeholder="Ex.: Revisar a matéria de Ciências; lembrar de levar cartolina; ideia para a apresentação..."></textarea><button id="ideasPinBtn" type="button">Fixar no quadro</button>`;old.before(composer)}}}
if(!$i('openIdeasTool').dataset.boundV2){$i('openIdeasTool').dataset.boundV2='1';$i('openIdeasTool').onclick=()=>{$i('studyHome').classList.add('hidden');['studyCalculator','studyDocument','studyRandomizer','studyFlashcards','studyMindmap','studyPeriodic'].forEach(id=>$i(id)?.classList.add('hidden'));$i('studyIdeas').classList.remove('hidden');load()};$i('ideasBack').onclick=()=>{$i('studyIdeas').classList.add('hidden');$i('studyHome').classList.remove('hidden')};$i('ideasPinBtn').onclick=addFromComposer;$i('ideaComposerText').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')addFromComposer()};$i('ideasSave').onclick=()=>save().then(()=>toast('Quadro salvo ✓'));$i('ideasClearMine').onclick=clearMine;$i('studyScope')?.addEventListener('change',()=>{if(!$i('studyIdeas').classList.contains('hidden'))load()});bindComposer()}return true}
function wait(){if(mount())return;const o=new MutationObserver(()=>{if(mount())o.disconnect()});o.observe(document.documentElement,{childList:true,subtree:true})}
wait();dbI.auth.onAuthStateChange((_e,s)=>{if(!s){meI=null;board=null;notes=[]}})
