import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'
import { CONFIG } from './config.js'
const dbI=createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}})
const $i=id=>document.getElementById(id)
let meI=null,board=null,notes=[],saveTimer=null,channel=null
function css(){if(document.querySelector('link[href^="study-ideas.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='study-ideas.css?v=1';document.head.appendChild(l)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const x=$i('toast');if(!x)return;x.textContent=t;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),1600)}
async function identity(){if(meI)return meI;const {data:{user}}=await dbI.auth.getUser();if(!user)throw new Error('Sem sessão');const {data,error}=await dbI.from('family_members').select('id,family_id,display_name').eq('auth_user_id',user.id).eq('active',true).single();if(error)throw error;meI=data;return data}
function scopeInfo(){const v=$i('studyScope')?.value||'private';return v==='private'?{conversation_id:null,visibility:'private'}:{conversation_id:v,visibility:'group'}}
function render(){const c=$i('ideasCanvas');if(!c)return;c.innerHTML=notes.map((n,idx)=>`<article class="idea-note" data-tone="${esc(n.tone||'pink')}"><div class="idea-note-head"><select data-tone-select="${idx}"><option value="pink" ${n.tone==='pink'?'selected':''}>Rosa</option><option value="lilac" ${n.tone==='lilac'?'selected':''}>Lilás</option><option value="blue" ${n.tone==='blue'?'selected':''}>Azul</option><option value="mint" ${n.tone==='mint'?'selected':''}>Menta</option><option value="yellow" ${n.tone==='yellow'?'selected':''}>Amarelo</option></select><button type="button" data-remove-note="${idx}" title="Excluir">✕</button></div><textarea data-note-text="${idx}" placeholder="Digite uma ideia...">${esc(n.text||'')}</textarea><small>${esc(n.by||'')}</small></article>`).join('')||'<p class="muted">Clique em “Nova ideia” para começar.</p>';document.querySelectorAll('[data-note-text]').forEach(x=>x.oninput=e=>{notes[+e.target.dataset.noteText].text=e.target.value;schedule()});document.querySelectorAll('[data-tone-select]').forEach(x=>x.onchange=e=>{notes[+e.target.dataset.toneSelect].tone=e.target.value;render();schedule()});document.querySelectorAll('[data-remove-note]').forEach(x=>x.onclick=()=>{notes.splice(+x.dataset.removeNote,1);render();schedule()})}
async function load(){await identity();board=null;notes=[];if(channel){dbI.removeChannel(channel);channel=null}const si=scopeInfo();let q=dbI.from('study_items').select('id,title,content,conversation_id,visibility,updated_at').eq('item_type','idea_board').eq('title','Quadro de Ideias');q=si.visibility==='private'?q.eq('owner_member_id',meI.id).is('conversation_id',null).eq('visibility','private'):q.eq('conversation_id',si.conversation_id).eq('visibility','group');const {data,error}=await q.order('updated_at',{ascending:false}).limit(1);if(error){console.error(error);return}board=data?.[0]||null;notes=Array.isArray(board?.content?.notes)?board.content.notes:[];render();$i('ideasStatus').textContent=board?'Salvo ✓':'Novo quadro';if(board){channel=dbI.channel(`ideas-${board.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'study_items',filter:`id=eq.${board.id}`},payload=>{if(document.activeElement?.matches?.('[data-note-text]'))return;notes=Array.isArray(payload.new?.content?.notes)?payload.new.content.notes:[];render();$i('ideasStatus').textContent='Atualizado em tempo real ✓'}).subscribe()}}
function schedule(){$i('ideasStatus').textContent='Salvando…';clearTimeout(saveTimer);saveTimer=setTimeout(save,650)}
async function save(){await identity();clearTimeout(saveTimer);const si=scopeInfo();if(!board){const {data,error}=await dbI.from('study_items').insert({family_id:meI.family_id,conversation_id:si.conversation_id,owner_member_id:meI.id,item_type:'idea_board',title:'Quadro de Ideias',content:{notes},visibility:si.visibility,allowed_member_ids:[],updated_by:meI.id}).select('id,title,content,conversation_id,visibility,updated_at').single();if(error){console.error(error);$i('ideasStatus').textContent='Erro ao salvar';return}board=data;await load()}else{const {error}=await dbI.from('study_items').update({content:{notes},updated_by:meI.id}).eq('id',board.id);if(error){console.error(error);$i('ideasStatus').textContent='Erro ao salvar';return}}$i('ideasStatus').textContent='Salvo ✓'}
function addNote(){notes.push({id:crypto.randomUUID(),text:'',tone:['pink','lilac','blue','mint','yellow'][notes.length%5],by:meI?.display_name||''});render();document.querySelectorAll('[data-note-text]')[notes.length-1]?.focus();schedule()}
function mount(){css();const grid=document.querySelector('.study-home-grid'),panel=$i('studyPanel');if(!grid||!panel)return false;if(!$i('openIdeasTool')){const b=document.createElement('button');b.id='openIdeasTool';b.type='button';b.className='study-tool-card';b.style.background='linear-gradient(145deg,#fff0bd,#ffddea 48%,#e6dbff)';b.innerHTML='<span class="tool-symbol">💡</span><strong>Quadro de Ideias</strong><small>Post-its para brainstorm individual ou colaborativo.</small>';grid.appendChild(b)}if(!$i('studyIdeas')){const s=document.createElement('div');s.id='studyIdeas';s.className='study-workspace hidden';s.innerHTML=`<button id="ideasBack" class="study-back" type="button">← Mesa de Estudos</button><div class="ideas-shell"><section class="ideas-board"><div class="ideas-top"><h3>Quadro de Ideias</h3><span id="ideasStatus" class="ideas-status">Carregando…</span><button id="ideasAdd" type="button">＋ Nova ideia</button><button id="ideasSave" type="button">Salvar agora</button></div><div id="ideasCanvas" class="ideas-canvas"></div></section></div>`;panel.appendChild(s)}if(!$i('openIdeasTool').dataset.bound){$i('openIdeasTool').dataset.bound='1';$i('openIdeasTool').onclick=()=>{$i('studyHome').classList.add('hidden');['studyCalculator','studyDocument','studyRandomizer','studyFlashcards'].forEach(id=>$i(id)?.classList.add('hidden'));$i('studyIdeas').classList.remove('hidden');load()};$i('ideasBack').onclick=()=>{$i('studyIdeas').classList.add('hidden');$i('studyHome').classList.remove('hidden')};$i('ideasAdd').onclick=async()=>{await identity();addNote()};$i('ideasSave').onclick=()=>save().then(()=>toast('Quadro salvo ✓'));$i('studyScope')?.addEventListener('change',()=>{if(!$i('studyIdeas').classList.contains('hidden'))load()})}return true}
function wait(){if(mount())return;const o=new MutationObserver(()=>{if(mount())o.disconnect()});o.observe(document.documentElement,{childList:true,subtree:true})}
wait();dbI.auth.onAuthStateChange((_e,s)=>{if(!s){meI=null;board=null;notes=[]}})
